//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FI_ZHCGDISPOSALS
    {
        public decimal DISPOSALID { get; set; }
        public string TASKNUM { get; set; }
        public string TYPE { get; set; }
        public string INFO { get; set; }
        public string MEMO { get; set; }
        public string UNITID { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
    }
}
