//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZHCGEntities : DbContext
    {
        public ZHCGEntities()
            : base("name=ZHCGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<FI_ZHCGMEDIAS> FI_ZHCGMEDIAS { get; set; }
        public DbSet<FI_ZHCGTASKS> FI_ZHCGTASKS { get; set; }
        public DbSet<FI_ZHCGDISPOSALS> FI_ZHCGDISPOSALS { get; set; }
    }
}
