//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taizhou.PLE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACITIVITYDEFINITION
    {
        public ACITIVITYDEFINITION()
        {
            this.ACTIVITYINSTANCES = new HashSet<ACTIVITYINSTANCE>();
            this.ACTIVITYPERMISSIONS = new HashSet<ACTIVITYPERMISSION>();
            this.DOCDEFINITIONRELATIONS = new HashSet<DOCDEFINITIONRELATION>();
        }
    
        public decimal ADID { get; set; }
        public Nullable<decimal> WDID { get; set; }
        public string ADNAME { get; set; }
        public string ADDESC { get; set; }
        public Nullable<decimal> TIMELIMITS { get; set; }
    
        public virtual WORKFLOWDEFINITION WORKFLOWDEFINITION { get; set; }
        public virtual ICollection<ACTIVITYINSTANCE> ACTIVITYINSTANCES { get; set; }
        public virtual ICollection<ACTIVITYPERMISSION> ACTIVITYPERMISSIONS { get; set; }
        public virtual ICollection<DOCDEFINITIONRELATION> DOCDEFINITIONRELATIONS { get; set; }
    }
}
