//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taizhou.PLE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVITYPEROPERTy
    {
        public string APID { get; set; }
        public string AIID { get; set; }
        public string KEY { get; set; }
        public string VALUE { get; set; }
        public string ASSEMBLYNAME { get; set; }
        public string TYPENAME { get; set; }
    
        public virtual ACTIVITYINSTANCE ACTIVITYINSTANCE { get; set; }
    }
}
