//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taizhou.PLE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVITYINSTANCE
    {
        public ACTIVITYINSTANCE()
        {
            this.ACTIVITYINSTANCES1 = new HashSet<ACTIVITYINSTANCE>();
            this.ACTIVITYPEROPERTIES = new HashSet<ACTIVITYPEROPERTy>();
            this.DOCINSTANCES = new HashSet<DOCINSTANCE>();
        }
    
        public string AIID { get; set; }
        public Nullable<decimal> ADID { get; set; }
        public string WIID { get; set; }
        public string PREVIOUSAIID { get; set; }
        public Nullable<decimal> PROCESSUSERID { get; set; }
        public Nullable<System.DateTime> PROCESSTIME { get; set; }
        public Nullable<decimal> ACTIVITYSTATUSID { get; set; }
        public Nullable<decimal> ASSIGNUSERID { get; set; }
        public Nullable<System.DateTime> DELIVERYTIME { get; set; }
        public Nullable<System.DateTime> EXPIRATIONTIME { get; set; }
        public Nullable<decimal> FROMUSERID { get; set; }
    
        public virtual ACITIVITYDEFINITION ACITIVITYDEFINITION { get; set; }
        public virtual ICollection<ACTIVITYINSTANCE> ACTIVITYINSTANCES1 { get; set; }
        public virtual ACTIVITYINSTANCE ACTIVITYINSTANCE1 { get; set; }
        public virtual ACTIVITYSTATUS ACTIVITYSTATUS { get; set; }
        public virtual WORKFLOWINSTANCE WORKFLOWINSTANCE { get; set; }
        public virtual ICollection<ACTIVITYPEROPERTy> ACTIVITYPEROPERTIES { get; set; }
        public virtual ICollection<DOCINSTANCE> DOCINSTANCES { get; set; }
    }
}
