//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taizhou.PLE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVITYPERMISSION
    {
        public decimal ADID { get; set; }
        public decimal REGIONID { get; set; }
        public Nullable<decimal> ACTIVITYPERMISSIONTYPEID { get; set; }
        public Nullable<decimal> USERID { get; set; }
        public Nullable<decimal> UNITID { get; set; }
        public Nullable<decimal> POSITIONID { get; set; }
    
        public virtual ACITIVITYDEFINITION ACITIVITYDEFINITION { get; set; }
        public virtual ACTIVITYPERMISSIONTYPE ACTIVITYPERMISSIONTYPE { get; set; }
        public virtual UNIT UNIT { get; set; }
    }
}
