//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taizhou.PLE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP
    {
        public APP()
        {
            this.MENUS = new HashSet<MENU>();
        }
    
        public decimal APPID { get; set; }
        public string APPNAME { get; set; }
    
        public virtual ICollection<MENU> MENUS { get; set; }
    }
}
