//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taizhou.PLE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAMERARELATION
    {
        public Nullable<decimal> CAMERAID { get; set; }
        public Nullable<decimal> CAMERATYPEID { get; set; }
        public Nullable<decimal> CONSTRSITEID { get; set; }
        public Nullable<decimal> DUMPINGSITEID { get; set; }
        public Nullable<decimal> CARID { get; set; }
        public decimal CAMERARELATIONID { get; set; }
    
        public virtual CAMERATYPE CAMERATYPE { get; set; }
        public virtual CAR CAR { get; set; }
        public virtual CONSTRSITE CONSTRSITE { get; set; }
        public virtual DUMPINGSITE DUMPINGSITE { get; set; }
        public virtual CAMERA CAMERA { get; set; }
    }
}
