//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taizhou.PLE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAMERATYPE
    {
        public CAMERATYPE()
        {
            this.CAMERARELATIONS = new HashSet<CAMERARELATION>();
            this.CAMERAS = new HashSet<CAMERA>();
        }
    
        public decimal CAMERATYPEID { get; set; }
        public string CAMERATYPENAME { get; set; }
    
        public virtual ICollection<CAMERARELATION> CAMERARELATIONS { get; set; }
        public virtual ICollection<CAMERA> CAMERAS { get; set; }
    }
}
