//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taizhou.PLE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAMERA
    {
        public CAMERA()
        {
            this.CAMERARELATIONS = new HashSet<CAMERARELATION>();
        }
    
        public decimal CAMERAID { get; set; }
        public string CAMERANAME { get; set; }
        public Nullable<decimal> CAMERATYPEID { get; set; }
        public Nullable<decimal> CONSTRSITEID { get; set; }
        public Nullable<decimal> DUMPINGSITEID { get; set; }
        public Nullable<decimal> CARID { get; set; }
        public string GEOMETRY { get; set; }
        public string PARAMETERS { get; set; }
        public string INDEXCODE { get; set; }
        public Nullable<System.DateTime> OBJECTTIME { get; set; }
    
        public virtual ICollection<CAMERARELATION> CAMERARELATIONS { get; set; }
        public virtual CAMERATYPE CAMERATYPE { get; set; }
        public virtual CAR CAR { get; set; }
        public virtual CONSTRSITE CONSTRSITE { get; set; }
        public virtual DUMPINGSITE DUMPINGSITE { get; set; }
    }
}
