//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taizhou.PLE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARALARMTYPE
    {
        public CARALARMTYPE()
        {
            this.CARALARMS = new HashSet<CARALARM>();
            this.CARLATESTPOSITIONS = new HashSet<CARLATESTPOSITION>();
        }
    
        public decimal CARALARMTYPEID { get; set; }
        public string CARALARMTYPENAME { get; set; }
    
        public virtual ICollection<CARALARM> CARALARMS { get; set; }
        public virtual ICollection<CARLATESTPOSITION> CARLATESTPOSITIONS { get; set; }
    }
}
