//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taizhou.PLE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARCOMPANy
    {
        public CARCOMPANy()
        {
            this.TRANSLICENSECARCOMPANIES = new HashSet<TRANSLICENSECARCOMPANy>();
        }
    
        public decimal CARCOMPANYID { get; set; }
        public string CARCOMPANYNAME { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<decimal> ISSYNO { get; set; }
        public Nullable<decimal> ISDELETED { get; set; }
        public Nullable<decimal> USERID { get; set; }
    
        public virtual USER USER { get; set; }
        public virtual ICollection<TRANSLICENSECARCOMPANy> TRANSLICENSECARCOMPANIES { get; set; }
    }
}
