//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taizhou.PLE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARLATESTPOSITION
    {
        public decimal CARID { get; set; }
        public System.DateTime POSITIONINGTIME { get; set; }
        public string WORKINGSTATE { get; set; }
        public Nullable<decimal> X { get; set; }
        public Nullable<decimal> Y { get; set; }
        public Nullable<decimal> SPEED { get; set; }
        public Nullable<decimal> DIRECTION { get; set; }
        public string STATUSDESC { get; set; }
        public Nullable<decimal> CARALARMTYPEID { get; set; }
        public Nullable<decimal> ACC { get; set; }
        public Nullable<decimal> ISHIGHQUALITY { get; set; }
    
        public virtual CARALARMTYPE CARALARMTYPE { get; set; }
        public virtual CAR CAR { get; set; }
    }
}
