//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taizhou.PLE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCDEFINITION
    {
        public DOCDEFINITION()
        {
            this.DOCDEFINITIONRELATIONS = new HashSet<DOCDEFINITIONRELATION>();
            this.DOCINSTANCES = new HashSet<DOCINSTANCE>();
        }
    
        public decimal DDID { get; set; }
        public string DDNAME { get; set; }
        public Nullable<decimal> ISREQUIRED { get; set; }
        public Nullable<decimal> ISAUTOBUILD { get; set; }
        public Nullable<decimal> ISUNIQUE { get; set; }
        public Nullable<decimal> SEQNO { get; set; }
        public Nullable<decimal> RELEVANT { get; set; }
    
        public virtual ICollection<DOCDEFINITIONRELATION> DOCDEFINITIONRELATIONS { get; set; }
        public virtual ICollection<DOCINSTANCE> DOCINSTANCES { get; set; }
    }
}
