//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taizhou.PLE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUMPINGSITE
    {
        public DUMPINGSITE()
        {
            this.CAMERARELATIONS = new HashSet<CAMERARELATION>();
            this.CAMERAS = new HashSet<CAMERA>();
            this.CARDRECORDS = new HashSet<CARDRECORD>();
            this.TRANSLICENSES = new HashSet<TRANSLICENS>();
        }
    
        public decimal DUMPINGSITEID { get; set; }
        public string DUMPINGSITENAME { get; set; }
        public Nullable<decimal> UNITID { get; set; }
        public string ADDRESS { get; set; }
        public string GEOMETRY { get; set; }
        public string OWNER { get; set; }
        public Nullable<System.DateTime> APPLIEDDATE { get; set; }
        public string CONTACT { get; set; }
        public string PHONE { get; set; }
        public Nullable<decimal> ISSYNC { get; set; }
        public Nullable<decimal> ISDELETED { get; set; }
    
        public virtual ICollection<CAMERARELATION> CAMERARELATIONS { get; set; }
        public virtual ICollection<CAMERA> CAMERAS { get; set; }
        public virtual ICollection<CARDRECORD> CARDRECORDS { get; set; }
        public virtual UNIT UNIT { get; set; }
        public virtual ICollection<TRANSLICENS> TRANSLICENSES { get; set; }
    }
}
