//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taizhou.PLE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GGFWTOZFDD
    {
        public decimal ID { get; set; }
        public Nullable<decimal> SSDD { get; set; }
        public string COMMENTS { get; set; }
        public Nullable<decimal> USERID { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public Nullable<decimal> EVENTID { get; set; }
        public string ARCHIVING { get; set; }
        public Nullable<decimal> ARCHIVINGUSER { get; set; }
        public Nullable<System.DateTime> ARCHIVINGTIME { get; set; }
    
        public virtual GGFWEVENT GGFWEVENT { get; set; }
    }
}
