//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taizhou.PLE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GGFWXFDOC
    {
        public string DOCID { get; set; }
        public string DOCURL { get; set; }
        public string DOCNAME { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public Nullable<decimal> EVETID { get; set; }
        public Nullable<decimal> CREATEUSERID { get; set; }
        public string DOCCODE { get; set; }
        public Nullable<decimal> TYPEID { get; set; }
    }
}
