//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taizhou.PLE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GGFWMONTHLYREPORT
    {
        public decimal MREPORTID { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public Nullable<decimal> GGFWSID { get; set; }
        public Nullable<decimal> CID { get; set; }
        public string FRACTION { get; set; }
    
        public virtual GGFWCASENAME GGFWCASENAME { get; set; }
        public virtual GGFWSOURCE GGFWSOURCE { get; set; }
    }
}
