//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taizhou.PLE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_CD_VIOCODE
    {
        public string WFXW { get; set; }
        public string XWMS { get; set; }
        public string WFYJ { get; set; }
        public string FKJE { get; set; }
        public Nullable<decimal> WFJFS { get; set; }
        public string XZCF { get; set; }
        public string QTCS { get; set; }
        public string WFYJ2 { get; set; }
        public string WFLB { get; set; }
        public string ZXBZ { get; set; }
        public string XWJX { get; set; }
    }
}
