//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taizhou.PLE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_CD_GOV
    {
        public string XZQH { get; set; }
        public string DWMC { get; set; }
        public string SSXZQH { get; set; }
        public string JB { get; set; }
        public string GBM { get; set; }
        public string JC { get; set; }
        public string CGDT { get; set; }
        public string JNDD { get; set; }
        public string FYDW { get; set; }
        public string SSDW { get; set; }
        public string ZXBZ { get; set; }
        public string DWDZ { get; set; }
        public string PZQH { get; set; }
        public string JDST { get; set; }
        public string TZPZT { get; set; }
        public string SLXX { get; set; }
        public string FWQH { get; set; }
        public string SKQH { get; set; }
        public string ZSDM { get; set; }
        public string ZSDWMC { get; set; }
        public string SKQC { get; set; }
        public string SKZH { get; set; }
        public string KHYH { get; set; }
        public string XMMC { get; set; }
        public string DDQH { get; set; }
    }
}
