//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taizhou.PLE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_USER_NEW
    {
        public string USERID { get; set; }
        public string ROLEID { get; set; }
        public string IUSERNAME { get; set; }
        public string IPASSWORD { get; set; }
        public string STATUS { get; set; }
        public string XZQH { get; set; }
        public string USERTYPE { get; set; }
        public string ZQMJ { get; set; }
        public string MJXM { get; set; }
        public string IP1 { get; set; }
        public string IP2 { get; set; }
        public string MAC1 { get; set; }
        public string MAC2 { get; set; }
    }
}
