//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taizhou.PLE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_VEH_VIOREC
    {
        public decimal XLH { get; set; }
        public string HPHM { get; set; }
        public string HPZL { get; set; }
        public string CSYS { get; set; }
        public Nullable<decimal> CWKC { get; set; }
        public Nullable<System.DateTime> WFSJ { get; set; }
        public Nullable<System.DateTime> HDLQSJ { get; set; }
        public Nullable<decimal> HDCXSJ { get; set; }
        public string CDBH { get; set; }
        public string FXBH { get; set; }
        public string CLLX { get; set; }
        public string WFXW { get; set; }
        public string WFXW2 { get; set; }
        public string WFNR { get; set; }
        public string WFNR2 { get; set; }
        public Nullable<decimal> CLSD { get; set; }
        public Nullable<decimal> CLXS { get; set; }
        public string SCZT { get; set; }
        public string JDZT { get; set; }
        public Nullable<System.DateTime> ZHCZSJ { get; set; }
        public string WFDD { get; set; }
        public string DDBH { get; set; }
        public string CJR { get; set; }
        public string JDR { get; set; }
        public Nullable<System.DateTime> JDRQ { get; set; }
        public string JDJG { get; set; }
        public string CLBH { get; set; }
        public string SBBH { get; set; }
        public string ZMS { get; set; }
        public string SJSS { get; set; }
        public string SJLY { get; set; }
        public string TPZT { get; set; }
        public string DZRY { get; set; }
        public string TZDH { get; set; }
        public string ZDXH { get; set; }
        public Nullable<System.DateTime> SJSCSJ { get; set; }
        public Nullable<System.DateTime> TPSCSJ { get; set; }
        public string TSCZR { get; set; }
        public string TSCZIP { get; set; }
        public string CLSYR { get; set; }
        public string ZSXXDZ { get; set; }
        public string YZBM { get; set; }
        public string SJHM { get; set; }
        public string DHHM { get; set; }
        public string DZYJ { get; set; }
        public string JSZH { get; set; }
        public string FZJG { get; set; }
        public string DSR { get; set; }
        public Nullable<System.DateTime> TZRQ { get; set; }
        public string TZR { get; set; }
        public Nullable<decimal> WFJFS { get; set; }
        public Nullable<decimal> FKJE { get; set; }
        public Nullable<decimal> ZNJ { get; set; }
        public string CLJG { get; set; }
        public string WFBH { get; set; }
        public Nullable<System.DateTime> CLSJ { get; set; }
        public string YYFS { get; set; }
        public string JDS { get; set; }
        public string CFR { get; set; }
        public string DSRSFZ { get; set; }
        public string DSRDZ { get; set; }
        public string DSRXZQH { get; set; }
        public string DSRDABH { get; set; }
        public string DSRDH { get; set; }
        public string DSRQTLXFS { get; set; }
        public string JKFS { get; set; }
        public string JSJQ { get; set; }
        public Nullable<decimal> SPJE { get; set; }
        public string SPR { get; set; }
        public Nullable<System.DateTime> SPSJ { get; set; }
        public string CLPP { get; set; }
        public string HCBZ { get; set; }
        public string ZCBZ { get; set; }
        public string CLFS { get; set; }
        public string BZ { get; set; }
        public string JSR { get; set; }
        public Nullable<System.DateTime> JSSJ { get; set; }
        public string CLGLBM { get; set; }
        public string CGDH { get; set; }
        public Nullable<decimal> SM { get; set; }
        public Nullable<decimal> ZJLX { get; set; }
        public string QTLJ { get; set; }
        public string JDCSFZM { get; set; }
        public string JDCYXQZ { get; set; }
        public string JDCZT { get; set; }
        public string FZSHR { get; set; }
        public Nullable<System.DateTime> FZSHSJ { get; set; }
        public string FZSHYJ { get; set; }
        public string CSBJ { get; set; }
        public string WFXH { get; set; }
        public string CWBZ { get; set; }
        public string FPHM { get; set; }
    }
}
