//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taizhou.PLE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEADERWEEKWORKPLAN
    {
        public decimal PLANID { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public string ONDUTYLEADER { get; set; }
        public string ONDUTYDEPT { get; set; }
        public Nullable<decimal> MODIFYUSERID { get; set; }
        public Nullable<System.DateTime> MODIFYTIME { get; set; }
        public Nullable<decimal> PLANUSERID { get; set; }
        public Nullable<System.DateTime> PLANTIME { get; set; }
    }
}
