//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taizhou.PLE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAPINFO
    {
        public decimal ID { get; set; }
        public Nullable<decimal> LAYERID { get; set; }
        public string ELEMENTID { get; set; }
        public string ELEMENTADDRESS { get; set; }
        public Nullable<decimal> MAPTYPE { get; set; }
        public string LONGLAT { get; set; }
        public Nullable<decimal> USERID { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public Nullable<decimal> STATE { get; set; }
        public string VALUEDATE { get; set; }
        public string CONTAIN { get; set; }
    }
}
