//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taizhou.PLE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESSAGE
    {
        public decimal MESSAGEID { get; set; }
        public Nullable<decimal> FROMUSERID { get; set; }
        public Nullable<decimal> TOUSERID { get; set; }
        public Nullable<decimal> TYPEID { get; set; }
        public string TITLE { get; set; }
        public string CONTENT { get; set; }
        public Nullable<System.DateTime> CREATEDTIME { get; set; }
        public Nullable<System.DateTime> READTIME { get; set; }
        public string SENDCHANNELS { get; set; }
        public string SMSNUMBER { get; set; }
        public decimal ISDELETED { get; set; }
    }
}
