//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taizhou.PLE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLE
    {
        public ROLE()
        {
            this.ROLEFUNCTIONS = new HashSet<ROLEFUNCTION>();
            this.USERROLES = new HashSet<USERROLE>();
        }
    
        public decimal ROLEID { get; set; }
        public string ROLENAME { get; set; }
        public Nullable<decimal> SEQNO { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<decimal> STATUSID { get; set; }
        public Nullable<decimal> APPID { get; set; }
    
        public virtual ICollection<ROLEFUNCTION> ROLEFUNCTIONS { get; set; }
        public virtual ICollection<USERROLE> USERROLES { get; set; }
    }
}
