//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taizhou.PLE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIMPLECASEPICTURE
    {
        public decimal SIMPLECASEID { get; set; }
        public Nullable<decimal> PICTURETYPE { get; set; }
        public byte[] PICTURE { get; set; }
        public decimal SIMPLECASEPICTUREID { get; set; }
    
        public virtual SIMPLECAS SIMPLECAS { get; set; }
    }
}
