//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taizhou.PLE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPECIALACTIVITYDEFINITON
    {
        public SPECIALACTIVITYDEFINITON()
        {
            this.SPECIALACTIVITICES = new HashSet<SPECIALACTIVITICE>();
            this.SPECIALWORKFLOWINSTANCES = new HashSet<SPECIALWORKFLOWINSTANCE>();
        }
    
        public decimal ADID { get; set; }
        public string NAME { get; set; }
    
        public virtual ICollection<SPECIALACTIVITICE> SPECIALACTIVITICES { get; set; }
        public virtual ICollection<SPECIALWORKFLOWINSTANCE> SPECIALWORKFLOWINSTANCES { get; set; }
    }
}
