//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taizhou.PLE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPECIALTOZFSJ
    {
        public string SPECIALAIID { get; set; }
        public string ZFSJWIID { get; set; }
        public Nullable<decimal> BIGCLASSID { get; set; }
        public Nullable<decimal> SMALLCLASSID { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public Nullable<decimal> CREATEUSERID { get; set; }
        public Nullable<decimal> STATEID { get; set; }
        public Nullable<decimal> ISCURRENT { get; set; }
        public Nullable<decimal> USERID { get; set; }
        public Nullable<System.DateTime> HANDLETIME { get; set; }
        public decimal ID { get; set; }
        public string ZXDCWIID { get; set; }
        public string ZXDCTITLE { get; set; }
    
        public virtual SPECIALACTIVITICE SPECIALACTIVITICE { get; set; }
        public virtual USER USER { get; set; }
    }
}
