//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taizhou.PLE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPECIALACTIVITICE
    {
        public SPECIALACTIVITICE()
        {
            this.SPECIALTOZFSJS = new HashSet<SPECIALTOZFSJ>();
        }
    
        public string AIID { get; set; }
        public string WIID { get; set; }
        public Nullable<decimal> ADID { get; set; }
        public Nullable<decimal> STATUS { get; set; }
        public Nullable<System.DateTime> CRETATIME { get; set; }
        public Nullable<decimal> USERID { get; set; }
        public Nullable<decimal> UNITID { get; set; }
        public Nullable<decimal> CREATEUSERID { get; set; }
        public string ADATA { get; set; }
    
        public virtual SPECIALACTIVITYDEFINITON SPECIALACTIVITYDEFINITON { get; set; }
        public virtual SPECIALWORKFLOWINSTANCE SPECIALWORKFLOWINSTANCE { get; set; }
        public virtual UNIT UNIT { get; set; }
        public virtual USER USER { get; set; }
        public virtual ICollection<SPECIALTOZFSJ> SPECIALTOZFSJS { get; set; }
    }
}
