//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taizhou.PLE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPECIALWORKFLOWINSTANCE
    {
        public SPECIALWORKFLOWINSTANCE()
        {
            this.SPECIALACTIVITICES = new HashSet<SPECIALACTIVITICE>();
        }
    
        public string WIID { get; set; }
        public string TITEL { get; set; }
        public string EXPLAIN { get; set; }
        public Nullable<System.DateTime> STARTTIME { get; set; }
        public Nullable<System.DateTime> OVERTIME { get; set; }
        public string FILES { get; set; }
        public Nullable<decimal> CREATEUSERID { get; set; }
        public Nullable<System.DateTime> CRETETIME { get; set; }
        public string WDATA { get; set; }
        public Nullable<decimal> STATUS { get; set; }
        public Nullable<decimal> ADID { get; set; }
    
        public virtual ICollection<SPECIALACTIVITICE> SPECIALACTIVITICES { get; set; }
        public virtual SPECIALACTIVITYDEFINITON SPECIALACTIVITYDEFINITON { get; set; }
        public virtual USER USER { get; set; }
    }
}
