//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taizhou.PLE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class STREETTYPE
    {
        public STREETTYPE()
        {
            this.STREETS = new HashSet<STREET>();
        }
    
        public decimal STREETTYPEID { get; set; }
        public string STREETTYPENAME { get; set; }
        public string STREETTYPEPONT { get; set; }
    
        public virtual ICollection<STREET> STREETS { get; set; }
    }
}
