//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taizhou.PLE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class STREETEXAMINE
    {
        public STREETEXAMINE()
        {
            this.STREETPROBLEMS = new HashSet<STREETPROBLEM>();
            this.STREETUSERS = new HashSet<STREETUSER>();
        }
    
        public decimal ID { get; set; }
        public Nullable<decimal> STREETBASEID { get; set; }
        public Nullable<decimal> STREETID { get; set; }
        public Nullable<decimal> STATUID { get; set; }
    
        public virtual STREETBAS STREETBAS { get; set; }
        public virtual STREET STREET { get; set; }
        public virtual ICollection<STREETPROBLEM> STREETPROBLEMS { get; set; }
        public virtual ICollection<STREETUSER> STREETUSERS { get; set; }
    }
}
