//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taizhou.PLE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class STREETBAS
    {
        public STREETBAS()
        {
            this.STREETEXAMINES = new HashSet<STREETEXAMINE>();
        }
    
        public decimal STREETBASEID { get; set; }
        public string ASSESSTITLE { get; set; }
        public string CONTENT { get; set; }
        public string FILES { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public Nullable<decimal> CREATEUSERID { get; set; }
        public Nullable<decimal> STATUID { get; set; }
        public string AUDITORUSERID { get; set; }
        public Nullable<System.DateTime> AUDITORTIME { get; set; }
        public string AUDITOPINION { get; set; }
    
        public virtual ICollection<STREETEXAMINE> STREETEXAMINES { get; set; }
    }
}
