//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taizhou.PLE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class STREETPROBLEM
    {
        public decimal ID { get; set; }
        public Nullable<decimal> STREETEXAMINEID { get; set; }
        public Nullable<decimal> REPORTID { get; set; }
        public string TITLE { get; set; }
        public string CONTENT { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public Nullable<decimal> BIGCLASSID { get; set; }
        public Nullable<decimal> SMALLCLASSID { get; set; }
        public Nullable<decimal> SUBCLASSID { get; set; }
        public Nullable<decimal> POINTSS { get; set; }
        public string DESCRIPTION { get; set; }
        public string LATANDLONG { get; set; }
        public string ADDRESS { get; set; }
        public string FILES { get; set; }
        public Nullable<decimal> TYPEID { get; set; }
        public Nullable<decimal> STATUID { get; set; }
        public Nullable<decimal> USERID { get; set; }
        public Nullable<System.DateTime> EXAMINETIME { get; set; }
        public string OPINION { get; set; }
        public Nullable<decimal> ACTUALPOINTS { get; set; }
    
        public virtual STREETEXAMINE STREETEXAMINE { get; set; }
    }
}
