//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taizhou.PLE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class STREET
    {
        public STREET()
        {
            this.STREETEXAMINES = new HashSet<STREETEXAMINE>();
        }
    
        public decimal STREETID { get; set; }
        public string STREETNAME { get; set; }
        public string STREETEXPLAIN { get; set; }
        public string STREETADDRESS { get; set; }
        public Nullable<decimal> UNITID { get; set; }
        public string STREETPERSON { get; set; }
        public string STREETCAPTAIN { get; set; }
        public Nullable<decimal> STREETTYPEID { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public Nullable<decimal> CREATEUSERID { get; set; }
        public Nullable<decimal> STATUID { get; set; }
    
        public virtual ICollection<STREETEXAMINE> STREETEXAMINES { get; set; }
        public virtual STREETTYPE STREETTYPE { get; set; }
    }
}
