//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taizhou.PLE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class STREESTORE
    {
        public decimal STREESTOREID { get; set; }
        public string SHOPNAME { get; set; }
        public string ADDRESS { get; set; }
        public string SHOPUSERNAME { get; set; }
        public string SHOPPHONE { get; set; }
        public string STREESTORETYPEID { get; set; }
        public Nullable<decimal> ISMTZP { get; set; }
        public Nullable<decimal> ISGSWSXKZ { get; set; }
        public Nullable<decimal> ISPSXKZ { get; set; }
        public Nullable<decimal> ISHJPL { get; set; }
        public string PICTUREURLS { get; set; }
        public string GEOMETRY { get; set; }
    
        public virtual STREESTORETYPE STREESTORETYPE { get; set; }
    }
}
