//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taizhou.PLE.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TZ_ZFJEntities : DbContext
    {
        public TZ_ZFJEntities()
            : base("name=TZ_ZFJEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<HT_CD_GOV> HT_CD_GOV { get; set; }
        public DbSet<HT_USER_NEW> HT_USER_NEW { get; set; }
        public DbSet<HT_VEH_VIOREC> HT_VEH_VIOREC { get; set; }
        public DbSet<HT_CD_ENUM> HT_CD_ENUM { get; set; }
        public DbSet<HT_CD_VIOCODE> HT_CD_VIOCODE { get; set; }
    }
}
