//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taizhou.PLE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNIT
    {
        public UNIT()
        {
            this.ACTIVITYPERMISSIONS = new HashSet<ACTIVITYPERMISSION>();
            this.CONSTRSITES = new HashSet<CONSTRSITE>();
            this.DUMPINGSITES = new HashSet<DUMPINGSITE>();
            this.SPECIALACTIVITICES = new HashSet<SPECIALACTIVITICE>();
            this.TRANSLICENSES = new HashSet<TRANSLICENS>();
            this.UNITS1 = new HashSet<UNIT>();
            this.USERS = new HashSet<USER>();
            this.WORKFLOWINSTANCES = new HashSet<WORKFLOWINSTANCE>();
            this.XCJGSIGNINS = new HashSet<XCJGSIGNIN>();
            this.ZFGKCARS = new HashSet<ZFGKCAR>();
        }
    
        public decimal UNITID { get; set; }
        public string UNITNAME { get; set; }
        public string PATH { get; set; }
        public Nullable<decimal> PARENTID { get; set; }
        public Nullable<decimal> UNITTYPEID { get; set; }
        public Nullable<decimal> STATUSID { get; set; }
        public Nullable<decimal> SEQNO { get; set; }
        public string DESCRIPTION { get; set; }
        public string ABBREVIATION { get; set; }
        public Nullable<decimal> ISADMINUNIT { get; set; }
        public string DWZC { get; set; }
    
        public virtual ICollection<ACTIVITYPERMISSION> ACTIVITYPERMISSIONS { get; set; }
        public virtual ICollection<CONSTRSITE> CONSTRSITES { get; set; }
        public virtual ICollection<DUMPINGSITE> DUMPINGSITES { get; set; }
        public virtual ICollection<SPECIALACTIVITICE> SPECIALACTIVITICES { get; set; }
        public virtual ICollection<TRANSLICENS> TRANSLICENSES { get; set; }
        public virtual ICollection<UNIT> UNITS1 { get; set; }
        public virtual UNIT UNIT1 { get; set; }
        public virtual UNITTYPE UNITTYPE { get; set; }
        public virtual ICollection<USER> USERS { get; set; }
        public virtual ICollection<WORKFLOWINSTANCE> WORKFLOWINSTANCES { get; set; }
        public virtual ICollection<XCJGSIGNIN> XCJGSIGNINS { get; set; }
        public virtual ICollection<ZFGKCAR> ZFGKCARS { get; set; }
    }
}
