//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taizhou.PLE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class XCJGSIGNIN
    {
        public Nullable<decimal> SSZDID { get; set; }
        public Nullable<System.DateTime> SIGNINDATE { get; set; }
        public string ADDRESSNAME { get; set; }
        public Nullable<decimal> STARTHOUR { get; set; }
        public Nullable<decimal> STARTMINUTE { get; set; }
        public Nullable<decimal> ENDHOUR { get; set; }
        public Nullable<decimal> ENDMINUTE { get; set; }
        public string GEOMETRY { get; set; }
        public decimal SIGNINID { get; set; }
        public Nullable<decimal> SIGNINTYPEID { get; set; }
        public string USERIDS { get; set; }
    
        public virtual UNIT UNIT { get; set; }
    }
}
