//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taizhou.PLE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class XCJGAREA
    {
        public XCJGAREA()
        {
            this.XCJGCARTASKS = new HashSet<XCJGCARTASK>();
            this.XCJGUSERTASKS = new HashSet<XCJGUSERTASK>();
        }
    
        public decimal AREAID { get; set; }
        public Nullable<decimal> SSDDID { get; set; }
        public Nullable<decimal> SSZDID { get; set; }
        public string AREANAME { get; set; }
        public string AREADESCRIPTION { get; set; }
        public string GEOMETRY { get; set; }
        public Nullable<decimal> AREAOWNERTYPE { get; set; }
        public Nullable<System.DateTime> XCTIME { get; set; }
        public string USERIDS { get; set; }
    
        public virtual ICollection<XCJGCARTASK> XCJGCARTASKS { get; set; }
        public virtual ICollection<XCJGUSERTASK> XCJGUSERTASKS { get; set; }
    }
}
