//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taizhou.PLE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class XZSPAPPROVALPROJECT
    {
        public decimal APID { get; set; }
        public Nullable<decimal> WDID { get; set; }
        public string APNAME { get; set; }
        public string APDESCRIPTION { get; set; }
        public string KZXX { get; set; }
        public string XCHCQK { get; set; }
        public Nullable<decimal> PROJECTID { get; set; }
    }
}
