//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taizhou.PLE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class XZSPSTU
    {
        public XZSPSTU()
        {
            this.XZSPACTISTS = new HashSet<XZSPACTIST>();
            this.XZSPWFISTS = new HashSet<XZSPWFIST>();
        }
    
        public decimal SID { get; set; }
        public string WSCODE { get; set; }
        public string WSNAME { get; set; }
        public string WSDESCRIPTION { get; set; }
    
        public virtual ICollection<XZSPACTIST> XZSPACTISTS { get; set; }
        public virtual ICollection<XZSPWFIST> XZSPWFISTS { get; set; }
    }
}
