//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taizhou.PLE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class XZSPWFISTS_DELETE
    {
        public string WIID { get; set; }
        public Nullable<decimal> WDID { get; set; }
        public Nullable<decimal> STATUSID { get; set; }
        public string CURRENTAIID { get; set; }
        public string WDATA { get; set; }
        public Nullable<System.DateTime> CREATEDTIME { get; set; }
        public string ZFZDNAME { get; set; }
        public string XZSPWSBH { get; set; }
        public string DTWZ { get; set; }
    }
}
