//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taizhou.PLE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class XZSPNEWTAB
    {
        public string AIID { get; set; }
        public Nullable<decimal> ADID { get; set; }
        public string PQR { get; set; }
        public Nullable<System.DateTime> PQSJ { get; set; }
        public string PQYJ { get; set; }
        public string ATTACHMENT1 { get; set; }
        public string ATTACHMENT2 { get; set; }
        public string ATTACHMENT3 { get; set; }
        public Nullable<decimal> STUTASID { get; set; }
        public string ID { get; set; }
        public Nullable<decimal> PQZD { get; set; }
    }
}
