//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taizhou.PLE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZBRZLIST
    {
        public string ID { get; set; }
        public string ZBRY { get; set; }
        public string SINGQK { get; set; }
        public string SBSJ { get; set; }
        public string COLUMN1DTWZ { get; set; }
        public Nullable<System.DateTime> CQDT { get; set; }
    }
}
