//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taizhou.PLE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZFGKCAR
    {
        public ZFGKCAR()
        {
            this.XCJGCARTASKS = new HashSet<XCJGCARTASK>();
            this.ZFGKCARHISTORYPOSITIONS = new HashSet<ZFGKCARHISTORYPOSITION>();
        }
    
        public decimal CARID { get; set; }
        public string CARNO { get; set; }
        public Nullable<decimal> UNITID { get; set; }
    
        public virtual UNIT UNIT { get; set; }
        public virtual ICollection<XCJGCARTASK> XCJGCARTASKS { get; set; }
        public virtual ICollection<ZFGKCARHISTORYPOSITION> ZFGKCARHISTORYPOSITIONS { get; set; }
        public virtual ZFGKCARLATESTPOSITION ZFGKCARLATESTPOSITION { get; set; }
    }
}
