//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taizhou.PLE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZFSJWORKFLOWINSTANCE
    {
        public ZFSJWORKFLOWINSTANCE()
        {
            this.GGFWTOZFZDS = new HashSet<GGFWTOZFZD>();
            this.ZFSJACTIVITYINSTANCES = new HashSet<ZFSJACTIVITYINSTANCE>();
        }
    
        public string WIID { get; set; }
        public Nullable<decimal> STATUSID { get; set; }
        public string CURRENTAIID { get; set; }
        public string WDATA { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public Nullable<decimal> USERID { get; set; }
        public Nullable<decimal> UNTIID { get; set; }
        public string PHONEID { get; set; }
        public Nullable<decimal> EVENTSOURCEID { get; set; }
        public string EVENTSOURCEPKID { get; set; }
    
        public virtual ICollection<GGFWTOZFZD> GGFWTOZFZDS { get; set; }
        public virtual ICollection<ZFSJACTIVITYINSTANCE> ZFSJACTIVITYINSTANCES { get; set; }
    }
}
