//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taizhou.PLE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZFSJCHECKWAY
    {
        public decimal ID { get; set; }
        public Nullable<decimal> PROCESSID { get; set; }
        public string CHECKNAME { get; set; }
        public string DESCRIPTION { get; set; }
    
        public virtual ZFSJPROCESSWAY ZFSJPROCESSWAY { get; set; }
    }
}
