//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taizhou.PLE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZFSJACTIVITYDEFINITION
    {
        public ZFSJACTIVITYDEFINITION()
        {
            this.ZFSJACTIVITYINSTANCES = new HashSet<ZFSJACTIVITYINSTANCE>();
        }
    
        public decimal ADID { get; set; }
        public string ADCODE { get; set; }
        public Nullable<decimal> NEXTADID { get; set; }
        public Nullable<System.DateTime> TIMELIMIT { get; set; }
        public string ADDESCRIPTION { get; set; }
        public string SEQNO { get; set; }
        public string ADNAME { get; set; }
    
        public virtual ICollection<ZFSJACTIVITYINSTANCE> ZFSJACTIVITYINSTANCES { get; set; }
    }
}
