//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taizhou.PLE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZFSJSUMMARYINFORMATION
    {
        public string WIID { get; set; }
        public string EVENTTITLE { get; set; }
        public string EVENTADDRESS { get; set; }
        public string EVENTSOURCE { get; set; }
        public string SSDD { get; set; }
        public string SSZD { get; set; }
        public string GEOMETRY { get; set; }
        public Nullable<System.DateTime> REPORTTIME { get; set; }
        public string REPORTPERSON { get; set; }
        public Nullable<decimal> UNITID { get; set; }
        public Nullable<decimal> USERID { get; set; }
        public string IMEICODE { get; set; }
    }
}
