//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HZW.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class bd_jcbjxx
    {
        public int jcsj_id { get; set; }
        public string jcsj_bh { get; set; }
        public string gslx_type { get; set; }
        public string jcsj_name { get; set; }
        public Nullable<decimal> swmx_id { get; set; }
        public string dltx { get; set; }
        public Nullable<decimal> zxdxzb { get; set; }
        public Nullable<decimal> zxdyzb { get; set; }
        public Nullable<decimal> gd { get; set; }
        public string sfyx { get; set; }
        public Nullable<System.DateTime> cjsj { get; set; }
        public string content { get; set; }
        public string deptname1 { get; set; }
    }
}
