//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HZW.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class event_zfsjs
    {
        public string event_id { get; set; }
        public string title { get; set; }
        public Nullable<System.DateTime> reporttime { get; set; }
        public string reportperson { get; set; }
        public string source { get; set; }
        public string contact { get; set; }
        public string content { get; set; }
        public string photo1 { get; set; }
        public string photo2 { get; set; }
        public string photo3 { get; set; }
        public string grometry { get; set; }
        public Nullable<int> isexamine { get; set; }
        public Nullable<int> inputperson { get; set; }
        public Nullable<System.DateTime> inputtime { get; set; }
        public string inputcontent { get; set; }
        public Nullable<int> invalisperson { get; set; }
        public Nullable<System.DateTime> invalistime { get; set; }
        public string invaliscontent { get; set; }
        public Nullable<int> ispush { get; set; }
    }
}
