//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HZW.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class fi_camera_item
    {
        public int thcid { get; set; }
        public Nullable<int> themeid { get; set; }
        public Nullable<int> sortnum { get; set; }
        public Nullable<int> cameraid { get; set; }
        public string name { get; set; }
        public string index_code { get; set; }
        public Nullable<int> camera_type { get; set; }
        public Nullable<double> longitude { get; set; }
        public Nullable<double> latitude { get; set; }
    }
}
