//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HZW.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class fi_camera_info
    {
        public int camera_id { get; set; }
        public Nullable<int> region_id { get; set; }
        public Nullable<int> device_id { get; set; }
        public string index_code { get; set; }
        public string name { get; set; }
        public Nullable<int> camera_type { get; set; }
        public Nullable<int> stream_type { get; set; }
        public Nullable<int> ptz_control_type { get; set; }
        public Nullable<int> pixel { get; set; }
        public Nullable<int> ptz_type { get; set; }
        public Nullable<int> sound { get; set; }
        public Nullable<int> is_enable { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<double> longitude { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<int> elevation { get; set; }
        public string install_place { get; set; }
        public string note { get; set; }
        public string parameter { get; set; }
        public string playback { get; set; }
        public string scope { get; set; }
    }
}
