//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HZW.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class fi_topatrollatestpos
    {
        public int patrolid { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
        public Nullable<double> coordinatex_84 { get; set; }
        public Nullable<double> coordinatey_84 { get; set; }
        public Nullable<double> coordinatex { get; set; }
        public Nullable<double> coordinatey { get; set; }
        public Nullable<int> stateid { get; set; }
        public Nullable<System.DateTime> datainsertdate { get; set; }
        public Nullable<System.DateTime> dataupdatedate { get; set; }
        public string coordtype { get; set; }
        public Nullable<int> syncflag { get; set; }
    }
}
