//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HZW.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class fi_torecmedias
    {
        public int recid { get; set; }
        public int msgid { get; set; }
        public int mediaid { get; set; }
        public string mediatype { get; set; }
        public string medianame { get; set; }
        public string mediausage { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public string mediaurl { get; set; }
        public Nullable<System.DateTime> datainsertdate { get; set; }
        public Nullable<System.DateTime> dataupdatedate { get; set; }
    }
}
