//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HZW.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class fi_tzcarlatestpositions
    {
        public int carid { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<System.DateTime> positioningdate { get; set; }
        public Nullable<double> x { get; set; }
        public Nullable<double> y { get; set; }
        public Nullable<double> speed { get; set; }
        public Nullable<double> direction { get; set; }
        public string gpsstate { get; set; }
        public Nullable<int> isparsed { get; set; }
        public string location { get; set; }
        public Nullable<int> isalarm { get; set; }
        public string alarmtype { get; set; }
        public string alarmdesc { get; set; }
    }
}
