//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HZW.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class fi_tchumans
    {
        public int humanid { get; set; }
        public string humanname { get; set; }
        public string humancode { get; set; }
        public Nullable<int> unitid { get; set; }
        public Nullable<int> regionid { get; set; }
        public Nullable<int> regiontype { get; set; }
        public string telmobile { get; set; }
        public string photourl { get; set; }
        public Nullable<int> validflag { get; set; }
        public Nullable<int> deleteflag { get; set; }
        public Nullable<System.DateTime> deletedate { get; set; }
        public Nullable<int> patrolflag { get; set; }
        public Nullable<System.DateTime> datainsertdate { get; set; }
        public Nullable<System.DateTime> dataupdatedate { get; set; }
        public Nullable<int> displayorder { get; set; }
        public Nullable<int> sex { get; set; }
    }
}
