//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HZW.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class fi_torecprocess
    {
        public int recid { get; set; }
        public int itemid { get; set; }
        public Nullable<System.DateTime> processdate { get; set; }
        public string humanname { get; set; }
        public string processname { get; set; }
        public string operationname { get; set; }
        public string processopinion { get; set; }
        public Nullable<System.DateTime> datainsertdate { get; set; }
        public Nullable<System.DateTime> dataupdatedate { get; set; }
        public Nullable<int> humanid { get; set; }
    }
}
