//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HZW.ZHCG.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hzwEntities : DbContext
    {
        public hzwEntities()
            : base("name=hzwEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ad_classes> ad_classes { get; set; }
        public DbSet<ad_outadverts> ad_outadverts { get; set; }
        public DbSet<base_menus> base_menus { get; set; }
        public DbSet<base_permissionmenus> base_permissionmenus { get; set; }
        public DbSet<base_permissions> base_permissions { get; set; }
        public DbSet<base_rolepermissions> base_rolepermissions { get; set; }
        public DbSet<base_roles> base_roles { get; set; }
        public DbSet<base_units> base_units { get; set; }
        public DbSet<base_unittypes> base_unittypes { get; set; }
        public DbSet<base_userroles> base_userroles { get; set; }
        public DbSet<base_users> base_users { get; set; }
        public DbSet<base_usertypes> base_usertypes { get; set; }
        public DbSet<bd_jcbjxx> bd_jcbjxx { get; set; }
        public DbSet<event_zfsjs> event_zfsjs { get; set; }
        public DbSet<fi_camera_dev> fi_camera_dev { get; set; }
        public DbSet<fi_camera_info> fi_camera_info { get; set; }
        public DbSet<fi_camera_item> fi_camera_item { get; set; }
        public DbSet<fi_camera_regions> fi_camera_regions { get; set; }
        public DbSet<fi_camera_theme> fi_camera_theme { get; set; }
        public DbSet<fi_camera_unit> fi_camera_unit { get; set; }
        public DbSet<fi_cardevicetypes> fi_cardevicetypes { get; set; }
        public DbSet<fi_carusagetypes> fi_carusagetypes { get; set; }
        public DbSet<fi_tchumans> fi_tchumans { get; set; }
        public DbSet<fi_tcpatrols> fi_tcpatrols { get; set; }
        public DbSet<fi_tcunits> fi_tcunits { get; set; }
        public DbSet<fi_tdeventsrcs> fi_tdeventsrcs { get; set; }
        public DbSet<fi_topatrollatestpos> fi_topatrollatestpos { get; set; }
        public DbSet<fi_topatrollogons> fi_topatrollogons { get; set; }
        public DbSet<fi_topatrolpos> fi_topatrolpos { get; set; }
        public DbSet<fi_torecmedias> fi_torecmedias { get; set; }
        public DbSet<fi_torecprocess> fi_torecprocess { get; set; }
        public DbSet<fi_torecs> fi_torecs { get; set; }
        public DbSet<fi_tzcarlatestpositions> fi_tzcarlatestpositions { get; set; }
        public DbSet<fi_tzcars> fi_tzcars { get; set; }
        public DbSet<mapelementcoord> mapelementcoords { get; set; }
        public DbSet<mapelement> mapelements { get; set; }
        public DbSet<mh_categors> mh_categors { get; set; }
        public DbSet<mh_news> mh_news { get; set; }
        public DbSet<project01> project01 { get; set; }
        public DbSet<project02> project02 { get; set; }
        public DbSet<project03> project03 { get; set; }
        public DbSet<store_bases> store_bases { get; set; }
        public DbSet<store_classes> store_classes { get; set; }
        public DbSet<sys_positions> sys_positions { get; set; }
        public DbSet<sys_regions> sys_regions { get; set; }
        public DbSet<sys_zd> sys_zd { get; set; }
    }
}
