//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HZW.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class project03
    {
        public string id { get; set; }
        public string msgId { get; set; }
        public string projectId { get; set; }
        public Nullable<int> length { get; set; }
        public Nullable<double> templ { get; set; }
        public Nullable<double> damp { get; set; }
        public Nullable<double> pm25 { get; set; }
        public Nullable<System.DateTime> formattedCreated { get; set; }
        public Nullable<System.DateTime> formattedUpdated { get; set; }
        public Nullable<double> x { get; set; }
        public Nullable<double> y { get; set; }
        public string address { get; set; }
    }
}
