//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HZW.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_zd
    {
        public int zd_id { get; set; }
        public string zd_type { get; set; }
        public string zd_bh { get; set; }
        public string zd_name { get; set; }
        public string bz { get; set; }
        public Nullable<int> sfgd { get; set; }
        public string icon { get; set; }
    }
}
