//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZHCGWebAPI.egovaService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://server.service.egova.com.cn/", ConfigurationName="egovaService.EgovaServiceSoap")]
    public interface EgovaServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        string process(string SPID, string SPPWD, string func, string request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<string> processAsync(string SPID, string SPPWD, string func, string request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EgovaServiceSoapChannel : ZHCGWebAPI.egovaService.EgovaServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EgovaServiceSoapClient : System.ServiceModel.ClientBase<ZHCGWebAPI.egovaService.EgovaServiceSoap>, ZHCGWebAPI.egovaService.EgovaServiceSoap {
        
        public EgovaServiceSoapClient() {
        }
        
        public EgovaServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EgovaServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EgovaServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EgovaServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string process(string SPID, string SPPWD, string func, string request) {
            return base.Channel.process(SPID, SPPWD, func, request);
        }
        
        public System.Threading.Tasks.Task<string> processAsync(string SPID, string SPPWD, string func, string request) {
            return base.Channel.processAsync(SPID, SPPWD, func, request);
        }
    }
}
