//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BD_JCFHLDDXX
    {
        public BD_JCFHLDDXX()
        {
            this.BD_JCFHLDDFHLDGX = new HashSet<BD_JCFHLDDFHLDGX>();
            this.BD_JCFHLDSSJDGX = new HashSet<BD_JCFHLDSSJDGX>();
        }
    
        public decimal JCFHLDD_ID { get; set; }
        public string JCFHLDDMS { get; set; }
        public Nullable<decimal> SWMX_ID { get; set; }
        public string DLTX { get; set; }
        public Nullable<decimal> ZXDXZB { get; set; }
        public Nullable<decimal> ZXDYZB { get; set; }
        public Nullable<decimal> GD { get; set; }
        public string SFYX { get; set; }
        public Nullable<System.DateTime> CJSJ { get; set; }
    
        public virtual ICollection<BD_JCFHLDDFHLDGX> BD_JCFHLDDFHLDGX { get; set; }
        public virtual ICollection<BD_JCFHLDSSJDGX> BD_JCFHLDSSJDGX { get; set; }
    }
}
