//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BD_JCLKLJLDGX
    {
        public decimal JCLKCXD_ID { get; set; }
        public decimal JCLDCXD_ID { get; set; }
        public string BZ { get; set; }
    
        public virtual BD_JCLDCXDXX BD_JCLDCXDXX { get; set; }
        public virtual BD_JCLKCXDXX BD_JCLKCXDXX { get; set; }
    }
}
