//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BD_JCQLXX
    {
        public BD_JCQLXX()
        {
            this.BD_JCQLSSJDGX = new HashSet<BD_JCQLSSJDGX>();
        }
    
        public decimal JCQL_ID { get; set; }
        public string JCQL_NAME { get; set; }
        public Nullable<decimal> SSJCLKLDCXD_ID { get; set; }
        public string SFYSWMX { get; set; }
        public Nullable<decimal> SWMX_ID { get; set; }
        public string DLTX { get; set; }
        public Nullable<decimal> ZXDXZB { get; set; }
        public Nullable<decimal> ZXDYZB { get; set; }
        public Nullable<decimal> GD { get; set; }
        public string SFYX { get; set; }
        public Nullable<System.DateTime> CJSJ { get; set; }
    
        public virtual BD_JCLKLDCXDXX BD_JCLKLDCXDXX { get; set; }
        public virtual ICollection<BD_JCQLSSJDGX> BD_JCQLSSJDGX { get; set; }
        public virtual BP_QLJCXX BP_QLJCXX { get; set; }
    }
}
