//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BD_JCLDCXDXX
    {
        public BD_JCLDCXDXX()
        {
            this.BD_JCLDRXDXX = new HashSet<BD_JCLDRXDXX>();
            this.BD_JCLKLJLDGX = new HashSet<BD_JCLKLJLDGX>();
        }
    
        public decimal JCLDCXD_ID { get; set; }
        public Nullable<decimal> SSJCDL_ID { get; set; }
        public Nullable<decimal> QDJCDL_ID { get; set; }
        public Nullable<decimal> ZDJCDL_ID { get; set; }
        public Nullable<decimal> QDJCLDCXD_ID { get; set; }
        public Nullable<decimal> ZDJCLDCXD_ID { get; set; }
        public Nullable<decimal> CXDCD { get; set; }
        public Nullable<decimal> CXDKD { get; set; }
        public Nullable<decimal> CXDMJ { get; set; }
        public Nullable<decimal> SWMX_ID { get; set; }
        public string DLTX { get; set; }
        public Nullable<decimal> ZXDXZB { get; set; }
        public Nullable<decimal> ZXDYZB { get; set; }
        public Nullable<decimal> GD { get; set; }
    
        public virtual BD_JCLKLDCXDXX BD_JCLKLDCXDXX { get; set; }
        public virtual ICollection<BD_JCLDRXDXX> BD_JCLDRXDXX { get; set; }
        public virtual ICollection<BD_JCLKLJLDGX> BD_JCLKLJLDGX { get; set; }
    }
}
