//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BD_JCHDXX
    {
        public BD_JCHDXX()
        {
            this.BD_JCSXHDJCXXGX = new HashSet<BD_JCSXHDJCXXGX>();
        }
    
        public decimal JCHD_ID { get; set; }
        public string JCHD_NAME { get; set; }
        public string SWMX_ID { get; set; }
        public Nullable<decimal> ZXDXZB { get; set; }
        public Nullable<decimal> ZXDYZB { get; set; }
        public Nullable<decimal> GD { get; set; }
        public string SFYX { get; set; }
        public Nullable<System.DateTime> CJSJ { get; set; }
    
        public virtual ICollection<BD_JCSXHDJCXXGX> BD_JCSXHDJCXXGX { get; set; }
        public virtual BP_HDJCXX BP_HDJCXX { get; set; }
    }
}
