//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BP_DLLDJCXX
    {
        public BP_DLLDJCXX()
        {
            this.BP_DLLDJCLKLDCXDGX = new HashSet<BP_DLLDJCLKLDCXDGX>();
        }
    
        public decimal DLLD_ID { get; set; }
        public string DLLD_NAME { get; set; }
        public string DLLDDJ_TYPE { get; set; }
        public string QYMS { get; set; }
        public Nullable<decimal> MJ { get; set; }
        public string CKJG { get; set; }
        public string BZ { get; set; }
        public Nullable<System.DateTime> JGRQ { get; set; }
        public Nullable<System.DateTime> YJRQ { get; set; }
        public Nullable<decimal> YHDW_ID { get; set; }
        public Nullable<decimal> SFLJSC { get; set; }
    
        public virtual ICollection<BP_DLLDJCLKLDCXDGX> BP_DLLDJCLKLDCXDGX { get; set; }
    }
}
