//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BP_GCSJXX
    {
        public decimal GC_SJID { get; set; }
        public Nullable<decimal> GC_ID { get; set; }
        public Nullable<System.DateTime> SJKSRQ { get; set; }
        public Nullable<System.DateTime> SJJSRQ { get; set; }
        public string SJDW { get; set; }
        public Nullable<decimal> SJGCJE { get; set; }
        public Nullable<decimal> SJKKJE { get; set; }
        public string SJSM { get; set; }
        public string TBR_ID { get; set; }
        public Nullable<System.DateTime> TBSJ { get; set; }
        public Nullable<System.DateTime> SSSJ { get; set; }
    
        public virtual BP_GCGKXX BP_GCGKXX { get; set; }
    }
}
