//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BP_GCZBXX
    {
        public decimal GC_ID { get; set; }
        public Nullable<System.DateTime> ZBRQ { get; set; }
        public string ZBFS_TYPE { get; set; }
        public string ZBFZR { get; set; }
        public Nullable<decimal> ZBJE { get; set; }
        public string ZBGS { get; set; }
        public string ZBGSFZR { get; set; }
        public string ZBGSLXDH { get; set; }
        public string JLGS { get; set; }
        public string JLGSFZR { get; set; }
        public string JLGSLXDH { get; set; }
        public string SJGS { get; set; }
        public string SJGSFZR { get; set; }
        public string SJGSLXDH { get; set; }
        public Nullable<System.DateTime> HTQDRQ { get; set; }
        public Nullable<decimal> HTJE { get; set; }
        public string ZLYQ { get; set; }
        public Nullable<decimal> BXQX { get; set; }
        public string GCTSYQ { get; set; }
        public string TBR_ID { get; set; }
        public Nullable<System.DateTime> TBSJ { get; set; }
        public string ZBDLR { get; set; }
        public string ZBLXR { get; set; }
        public string ZBLXDH { get; set; }
    
        public virtual BP_GCGKXX BP_GCGKXX { get; set; }
    }
}
