//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BP_GCXMFJ
    {
        public decimal ATID { get; set; }
        public Nullable<decimal> GC_ID { get; set; }
        public Nullable<decimal> GCGCZT_ID { get; set; }
        public string RZ_TYPE { get; set; }
        public Nullable<decimal> RZ_ID { get; set; }
        public string FJ_NAME { get; set; }
        public string FJLX_TYPE { get; set; }
        public string FJLB_TYPE { get; set; }
        public string FJDX { get; set; }
        public string FJLJ { get; set; }
        public Nullable<System.DateTime> CJRQ { get; set; }
    
        public virtual BP_GCGKXX BP_GCGKXX { get; set; }
    }
}
