//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BP_JGJCXX
    {
        public decimal JCJG_ID { get; set; }
        public string JGCZ_TYPE { get; set; }
        public string GG { get; set; }
        public string SCCJ { get; set; }
        public string ZJ { get; set; }
        public Nullable<System.DateTime> BJRQ { get; set; }
        public string CQDW { get; set; }
        public string JGZP { get; set; }
    
        public virtual BD_JCJGXX BD_JCJGXX { get; set; }
    }
}
