//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CQGL_PROJECTS
    {
        public CQGL_PROJECTS()
        {
            this.CQGL_ENTERPRISES = new HashSet<CQGL_ENTERPRISES>();
        }
    
        public decimal PROJECTID { get; set; }
        public string PROJECTNAME { get; set; }
        public string PROJECTUSER { get; set; }
        public Nullable<System.DateTime> STARTTIME { get; set; }
        public Nullable<System.DateTime> ENDTIME { get; set; }
        public string REMARKS { get; set; }
        public Nullable<decimal> STATE { get; set; }
        public string FILENAME { get; set; }
        public string FILEPATH { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public Nullable<decimal> CREATEUSER { get; set; }
        public string GEOMETRY { get; set; }
        public Nullable<decimal> HOUSEHOLDS { get; set; }
        public string PROJECTAREA { get; set; }
    
        public virtual ICollection<CQGL_ENTERPRISES> CQGL_ENTERPRISES { get; set; }
    }
}
