//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CQGL_HOUSES
    {
        public CQGL_HOUSES()
        {
            this.CQGL_DRAWS = new HashSet<CQGL_DRAWS>();
            this.CQGL_SIGNS = new HashSet<CQGL_SIGNS>();
            this.CQGL_TRANSITIONS = new HashSet<CQGL_TRANSITIONS>();
        }
    
        public decimal HOUSEID { get; set; }
        public Nullable<decimal> PROJECTID { get; set; }
        public string HOUSEHOLDER { get; set; }
        public string HOLDERPHONE { get; set; }
        public Nullable<decimal> WARRANTAREA { get; set; }
        public Nullable<decimal> MEASUREMENTAREA { get; set; }
        public Nullable<decimal> WITHOUTAREA { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public Nullable<decimal> CREATEUSER { get; set; }
    
        public virtual ICollection<CQGL_DRAWS> CQGL_DRAWS { get; set; }
        public virtual ICollection<CQGL_SIGNS> CQGL_SIGNS { get; set; }
        public virtual ICollection<CQGL_TRANSITIONS> CQGL_TRANSITIONS { get; set; }
    }
}
