//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CQGL_ENTERPRISEMONEYS
    {
        public decimal OMID { get; set; }
        public Nullable<decimal> ENTERPRISEID { get; set; }
        public Nullable<System.DateTime> PAYPALTIME { get; set; }
        public Nullable<decimal> PARPALMONEY { get; set; }
        public string REMARKS { get; set; }
        public string FILENAME { get; set; }
        public string FILEPATH { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public Nullable<decimal> CREATEUSER { get; set; }
    
        public virtual CQGL_ENTERPRISES CQGL_ENTERPRISES { get; set; }
    }
}
