//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FI_CAMERA_UNIT
    {
        public FI_CAMERA_UNIT()
        {
            this.FI_CAMERA_REGIONS = new HashSet<FI_CAMERA_REGIONS>();
        }
    
        public decimal UNITID { get; set; }
        public string UNITNAME { get; set; }
        public Nullable<decimal> PARENTID { get; set; }
        public string PATH { get; set; }
    
        public virtual ICollection<FI_CAMERA_REGIONS> FI_CAMERA_REGIONS { get; set; }
    }
}
