//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FI_CAMERA_REGIONS
    {
        public decimal REGIONID { get; set; }
        public string REGIONNAME { get; set; }
        public Nullable<decimal> UNITID { get; set; }
    
        public virtual FI_CAMERA_UNIT FI_CAMERA_UNIT { get; set; }
    }
}
