//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GCGL_SIMPLEGCAUDITS
    {
        public decimal AUDITID { get; set; }
        public string SIMPLEGCID { get; set; }
        public Nullable<decimal> AUDITUSER { get; set; }
        public Nullable<decimal> ISAGREE { get; set; }
        public string OPINION { get; set; }
        public string REMARKS { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public Nullable<System.DateTime> AUDITTIME { get; set; }
    }
}
