//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GCGL_SIMPLES
    {
        public string SIMPLEGCID { get; set; }
        public string GCNAME { get; set; }
        public string GCNUMBER { get; set; }
        public Nullable<System.DateTime> STARTTIME { get; set; }
        public Nullable<System.DateTime> ENDTIME { get; set; }
        public string CONTENT { get; set; }
        public string WORKPLAN { get; set; }
        public Nullable<decimal> MONEY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public Nullable<decimal> CREATEUSER { get; set; }
        public string GEOMETRY { get; set; }
    }
}
