//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OA_CONTACTGROUPS
    {
        public OA_CONTACTGROUPS()
        {
            this.OA_CONTACTS = new HashSet<OA_CONTACTS>();
        }
    
        public decimal CONTACTGROUPID { get; set; }
        public string CONTACTGROUPNAME { get; set; }
        public Nullable<decimal> SEQNO { get; set; }
        public Nullable<decimal> CREATEDUSERID { get; set; }
    
        public virtual ICollection<OA_CONTACTS> OA_CONTACTS { get; set; }
    }
}
