//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OA_MEETINGADDRESSES
    {
        public OA_MEETINGADDRESSES()
        {
            this.OA_MEETINGS = new HashSet<OA_MEETINGS>();
        }
    
        public decimal ADDRESSID { get; set; }
        public string ADDRESSNAME { get; set; }
        public Nullable<decimal> SEQ { get; set; }
        public string REMARK { get; set; }
    
        public virtual ICollection<OA_MEETINGS> OA_MEETINGS { get; set; }
    }
}
