//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OA_NOTICES
    {
        public OA_NOTICES()
        {
            this.OA_USERNOTICES = new HashSet<OA_USERNOTICES>();
        }
    
        public decimal NOTICEID { get; set; }
        public string NOTICETITLE { get; set; }
        public string NOTICETYPE { get; set; }
        public string AUTHOR { get; set; }
        public string CONTENT { get; set; }
        public Nullable<System.DateTime> CREATEDTIME { get; set; }
        public Nullable<decimal> CREATEDUSER { get; set; }
        public Nullable<decimal> STATUS { get; set; }
        public string FILENAME { get; set; }
        public string FILEPATH { get; set; }
    
        public virtual ICollection<OA_USERNOTICES> OA_USERNOTICES { get; set; }
    }
}
