//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OA_SCHEDULES
    {
        public decimal SCHEDULEID { get; set; }
        public Nullable<decimal> OWNER { get; set; }
        public string TITLE { get; set; }
        public string CONTENT { get; set; }
        public string SCHEDULESOURCE { get; set; }
        public Nullable<System.DateTime> STARTTIME { get; set; }
        public Nullable<System.DateTime> ENDTIME { get; set; }
        public Nullable<decimal> SHARETYPEID { get; set; }
        public Nullable<decimal> CREATEDUSERID { get; set; }
        public Nullable<System.DateTime> CREATEDITME { get; set; }
    }
}
