//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OA_USERFILES
    {
        public decimal UFID { get; set; }
        public Nullable<decimal> FILEID { get; set; }
        public Nullable<decimal> USERID { get; set; }
        public Nullable<decimal> ISREAD { get; set; }
        public Nullable<decimal> ISRESPONSE { get; set; }
        public string RESPONSECONTENT { get; set; }
        public Nullable<decimal> TRANSMIT { get; set; }
        public Nullable<decimal> ISFINISH { get; set; }
    
        public virtual OA_FILES OA_FILES { get; set; }
    }
}
