//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QWGL_ALARMMEMORYLOCATIONDATA
    {
        public decimal ID { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public Nullable<decimal> LONGITUDE { get; set; }
        public Nullable<decimal> LATITUDE { get; set; }
        public Nullable<decimal> X { get; set; }
        public Nullable<decimal> Y { get; set; }
        public Nullable<System.DateTime> GPSTIME { get; set; }
        public Nullable<decimal> SPEED { get; set; }
        public Nullable<System.DateTime> ALARMSTRATTIME { get; set; }
        public Nullable<System.DateTime> ALARMENDTIME { get; set; }
        public Nullable<decimal> ALARMTYPE { get; set; }
        public Nullable<decimal> USERID { get; set; }
        public Nullable<decimal> STATE { get; set; }
        public string CONTENT { get; set; }
        public Nullable<System.DateTime> DEALTIME { get; set; }
        public Nullable<decimal> DEALUSERID { get; set; }
        public Nullable<decimal> ISALLEGE { get; set; }
        public string ALLEGEREASON { get; set; }
        public Nullable<System.DateTime> ALLEGETIME { get; set; }
        public Nullable<decimal> ISCONTINUED { get; set; }
    
        public virtual SYS_USERS SYS_USERS { get; set; }
    }
}
