//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QWGL_LEAVEEXAMINES
    {
        public decimal LEID { get; set; }
        public Nullable<decimal> LEAVEID { get; set; }
        public Nullable<decimal> EXUSERID { get; set; }
        public string EXCONTENT { get; set; }
        public Nullable<decimal> EXRESULT { get; set; }
        public Nullable<System.DateTime> EXTIME { get; set; }
        public string REMARK { get; set; }
    
        public virtual QWGL_LEAVES QWGL_LEAVES { get; set; }
    }
}
