//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QWGL_USERSIGNINS
    {
        public decimal SIGNINID { get; set; }
        public Nullable<decimal> USERID { get; set; }
        public Nullable<System.DateTime> SIGNINTIME { get; set; }
        public Nullable<decimal> X84 { get; set; }
        public Nullable<decimal> Y84 { get; set; }
        public Nullable<decimal> X2000 { get; set; }
        public Nullable<decimal> Y2000 { get; set; }
        public string REMARK { get; set; }
    }
}
