//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QWGL_CARTASKS
    {
        public QWGL_CARTASKS()
        {
            this.QWGL_CARTASKRAREARS = new HashSet<QWGL_CARTASKRAREARS>();
        }
    
        public decimal CARTASKID { get; set; }
        public Nullable<decimal> CARID { get; set; }
        public Nullable<System.DateTime> SDATE { get; set; }
        public Nullable<System.DateTime> EDATE { get; set; }
        public string TASKCONTENT { get; set; }
        public Nullable<System.DateTime> CREATEDTIME { get; set; }
        public Nullable<decimal> CRETEUSERID { get; set; }
    
        public virtual ICollection<QWGL_CARTASKRAREARS> QWGL_CARTASKRAREARS { get; set; }
    }
}
