//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QWGL_USERTASKAREARS
    {
        public decimal UTARID { get; set; }
        public Nullable<decimal> USERTASKID { get; set; }
        public Nullable<decimal> AREAID { get; set; }
    
        public virtual QWGL_AREAS QWGL_AREAS { get; set; }
        public virtual QWGL_USERTASKS QWGL_USERTASKS { get; set; }
    }
}
