//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QWGL_USERTASKS
    {
        public QWGL_USERTASKS()
        {
            this.QWGL_USERSIGNINTASKS = new HashSet<QWGL_USERSIGNINTASKS>();
            this.QWGL_USERTASKAREARS = new HashSet<QWGL_USERTASKAREARS>();
        }
    
        public decimal USERTASKID { get; set; }
        public Nullable<decimal> USERID { get; set; }
        public Nullable<System.DateTime> SDATE { get; set; }
        public Nullable<System.DateTime> EDATE { get; set; }
        public string TASKCONTENT { get; set; }
        public Nullable<System.DateTime> CREATEDTIME { get; set; }
        public Nullable<decimal> CRETEUSERID { get; set; }
    
        public virtual ICollection<QWGL_USERSIGNINTASKS> QWGL_USERSIGNINTASKS { get; set; }
        public virtual ICollection<QWGL_USERTASKAREARS> QWGL_USERTASKAREARS { get; set; }
    }
}
