//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_ROLES
    {
        public SYS_ROLES()
        {
            this.SYS_ROLEFUNCTIONS = new HashSet<SYS_ROLEFUNCTIONS>();
            this.SYS_USERROLES = new HashSet<SYS_USERROLES>();
        }
    
        public decimal ROLEID { get; set; }
        public string ROLENAME { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<decimal> STATUSID { get; set; }
        public Nullable<decimal> SEQNUM { get; set; }
    
        public virtual ICollection<SYS_ROLEFUNCTIONS> SYS_ROLEFUNCTIONS { get; set; }
        public virtual ICollection<SYS_USERROLES> SYS_USERROLES { get; set; }
    }
}
