//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_IDENTITYS
    {
        public SYS_IDENTITYS()
        {
            this.WJGL_NONBUILDINGS = new HashSet<WJGL_NONBUILDINGS>();
        }
    
        public decimal IDENTITYID { get; set; }
        public string IDENTITYNAME { get; set; }
        public string REMARKS { get; set; }
    
        public virtual ICollection<WJGL_NONBUILDINGS> WJGL_NONBUILDINGS { get; set; }
    }
}
