//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_UNITS
    {
        public SYS_UNITS()
        {
            this.QWGL_CARS = new HashSet<QWGL_CARS>();
            this.SYS_USERS = new HashSet<SYS_USERS>();
        }
    
        public decimal UNITID { get; set; }
        public string UNITNAME { get; set; }
        public string PATH { get; set; }
        public Nullable<decimal> PARENTID { get; set; }
        public Nullable<decimal> UNITTYPEID { get; set; }
        public Nullable<decimal> STATUSID { get; set; }
        public string DESCRIPTION { get; set; }
        public string ABBREVIATION { get; set; }
        public Nullable<decimal> SEQNUM { get; set; }
    
        public virtual ICollection<QWGL_CARS> QWGL_CARS { get; set; }
        public virtual SYS_UNITTYPES SYS_UNITTYPES { get; set; }
        public virtual ICollection<SYS_USERS> SYS_USERS { get; set; }
    }
}
