//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TJ_ZONEENENT_TODAY
    {
        public decimal ZONEID { get; set; }
        public System.DateTime STATTIME { get; set; }
        public string ZONENAME { get; set; }
        public Nullable<decimal> PATROLRCOUNT { get; set; }
        public Nullable<decimal> SMARTCOUNT { get; set; }
        public Nullable<decimal> PATROLCLOSEDCOUNT { get; set; }
        public Nullable<decimal> SENTCLOSEDCOUNT { get; set; }
    }
}
