//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_TJ_XTGL_ZFSJS
    {
        public string ZFSJID { get; set; }
        public Nullable<System.DateTime> CREATETTIME { get; set; }
        public Nullable<System.DateTime> OVERTIME { get; set; }
        public Nullable<decimal> SOURCEID { get; set; }
        public Nullable<decimal> ZONEID { get; set; }
        public Nullable<decimal> CREATEUSERID { get; set; }
        public Nullable<decimal> BCLASSID { get; set; }
        public Nullable<decimal> SCLASSID { get; set; }
        public string CURRENTWFSAID { get; set; }
        public string WFSAID { get; set; }
        public string WFSID { get; set; }
        public string WFDNAME { get; set; }
        public Nullable<System.DateTime> DEALTIME { get; set; }
    }
}
