//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_WORKFLOWS
    {
        public WF_WORKFLOWS()
        {
            this.WF_WORKFLOWDETAILS = new HashSet<WF_WORKFLOWDETAILS>();
            this.WF_WORKFLOWSPECIFICS = new HashSet<WF_WORKFLOWSPECIFICS>();
        }
    
        public string WFID { get; set; }
        public string WFNAME { get; set; }
        public decimal WFTYPEID { get; set; }
        public Nullable<decimal> CREATEUSERID { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public Nullable<decimal> STATUS { get; set; }
        public string TABLENAME { get; set; }
        public string WFPIC { get; set; }
    
        public virtual ICollection<WF_WORKFLOWDETAILS> WF_WORKFLOWDETAILS { get; set; }
        public virtual ICollection<WF_WORKFLOWSPECIFICS> WF_WORKFLOWSPECIFICS { get; set; }
    }
}
