//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_WORKFLOWSPECIFICACTIVITYS
    {
        public WF_WORKFLOWSPECIFICACTIVITYS()
        {
            this.WF_WORKFLOWSPECIFICUSERS = new HashSet<WF_WORKFLOWSPECIFICUSERS>();
        }
    
        public string WFSAID { get; set; }
        public string WFSID { get; set; }
        public Nullable<decimal> STATUS { get; set; }
        public Nullable<decimal> DEALUSERID { get; set; }
        public Nullable<System.DateTime> DEALTIME { get; set; }
        public string WFDID { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
    
        public virtual WF_WORKFLOWDETAILS WF_WORKFLOWDETAILS { get; set; }
        public virtual WF_WORKFLOWSPECIFICS WF_WORKFLOWSPECIFICS { get; set; }
        public virtual ICollection<WF_WORKFLOWSPECIFICUSERS> WF_WORKFLOWSPECIFICUSERS { get; set; }
    }
}
