//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WJGL_NONBUILDINGS
    {
        public string WJID { get; set; }
        public string WJUNIT { get; set; }
        public Nullable<decimal> STATE { get; set; }
        public Nullable<decimal> IDENTITYID { get; set; }
        public Nullable<decimal> ZONEID { get; set; }
        public string TEL { get; set; }
        public string MAPLOACTION { get; set; }
        public string WJADDRESS { get; set; }
        public Nullable<System.DateTime> WJTIME { get; set; }
        public string WJTYPE { get; set; }
        public string WJFRAME { get; set; }
        public Nullable<decimal> WJFLOOR { get; set; }
        public string LANDTYPE { get; set; }
        public string WJUSE { get; set; }
        public Nullable<decimal> LANDAREA { get; set; }
        public Nullable<decimal> BUILDINGAREA { get; set; }
        public Nullable<System.DateTime> REMOVETIME { get; set; }
        public Nullable<decimal> REMOVEAREA { get; set; }
        public string CONSTRUCTIONPROJECT { get; set; }
        public string SIXCASE { get; set; }
        public Nullable<decimal> RECTIFICATIONCASE { get; set; }
        public Nullable<System.DateTime> RECTIFICATIONTIME { get; set; }
        public string REMARK1 { get; set; }
        public string REMARK2 { get; set; }
        public string REMARK3 { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public Nullable<decimal> CREATEUSER { get; set; }
        public Nullable<decimal> X84 { get; set; }
        public Nullable<decimal> Y84 { get; set; }
        public Nullable<decimal> X2000 { get; set; }
        public Nullable<decimal> Y2000 { get; set; }
    
        public virtual SYS_IDENTITYS SYS_IDENTITYS { get; set; }
        public virtual SYS_ZONES SYS_ZONES { get; set; }
    }
}
