//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class XTGL_ZNBJSJS
    {
        public decimal ZNBJID { get; set; }
        public Nullable<decimal> EVENTID { get; set; }
        public Nullable<decimal> EVENTTYPE { get; set; }
        public Nullable<decimal> INPUTSOURCE { get; set; }
        public string INPUTSOURCEINDEXCODE { get; set; }
        public string EVENTNAME { get; set; }
        public string LOGID { get; set; }
        public Nullable<decimal> STATUS { get; set; }
        public Nullable<System.DateTime> HAPPENTIME { get; set; }
        public Nullable<System.DateTime> ENDTIME { get; set; }
        public Nullable<decimal> ISDEAL { get; set; }
        public Nullable<decimal> DEALUSERID { get; set; }
        public Nullable<System.DateTime> DEALTIME { get; set; }
        public string DEALCONTENT { get; set; }
        public Nullable<decimal> ISEFFECT { get; set; }
    }
}
