//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBZGM.XTBG.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NBZGMEntities : DbContext
    {
        public NBZGMEntities()
            : base("name=NBZGMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<SYS_FUNCTIONS> SYS_FUNCTIONS { get; set; }
        public DbSet<SYS_IDENTITYS> SYS_IDENTITYS { get; set; }
        public DbSet<SYS_PHOTECAROUSELS> SYS_PHOTECAROUSELS { get; set; }
        public DbSet<SYS_ROLEFUNCTIONS> SYS_ROLEFUNCTIONS { get; set; }
        public DbSet<SYS_ROLES> SYS_ROLES { get; set; }
        public DbSet<SYS_UNITS> SYS_UNITS { get; set; }
        public DbSet<SYS_UNITTYPES> SYS_UNITTYPES { get; set; }
        public DbSet<SYS_USERPOSITIONS> SYS_USERPOSITIONS { get; set; }
        public DbSet<SYS_USERROLES> SYS_USERROLES { get; set; }
        public DbSet<SYS_USERS> SYS_USERS { get; set; }
        public DbSet<SYS_ZDXX> SYS_ZDXX { get; set; }
        public DbSet<SYS_ZONES> SYS_ZONES { get; set; }
        public DbSet<OA_ATTRACHS> OA_ATTRACHS { get; set; }
        public DbSet<OA_CONTACTGROUPS> OA_CONTACTGROUPS { get; set; }
        public DbSet<OA_CONTACTS> OA_CONTACTS { get; set; }
        public DbSet<OA_EMAILS> OA_EMAILS { get; set; }
        public DbSet<OA_FILES> OA_FILES { get; set; }
        public DbSet<OA_FINANCEAUDITS> OA_FINANCEAUDITS { get; set; }
        public DbSet<OA_FINANCES> OA_FINANCES { get; set; }
        public DbSet<OA_MEETINGADDRESSES> OA_MEETINGADDRESSES { get; set; }
        public DbSet<OA_MEETINGS> OA_MEETINGS { get; set; }
        public DbSet<OA_NOTICES> OA_NOTICES { get; set; }
        public DbSet<OA_SCHEDULES> OA_SCHEDULES { get; set; }
        public DbSet<OA_TASKS> OA_TASKS { get; set; }
        public DbSet<OA_USEREMAILS> OA_USEREMAILS { get; set; }
        public DbSet<OA_USERFILES> OA_USERFILES { get; set; }
        public DbSet<OA_USERMEETINGS> OA_USERMEETINGS { get; set; }
        public DbSet<OA_USERNOTICES> OA_USERNOTICES { get; set; }
        public DbSet<XTBG_SCHEDULE> XTBG_SCHEDULE { get; set; }
        public DbSet<XTBG_MEETINGROOM> XTBG_MEETINGROOM { get; set; }
        public DbSet<XTBG_ATTACHMENT> XTBG_ATTACHMENT { get; set; }
        public DbSet<XTBG_SMS> XTBG_SMS { get; set; }
        public DbSet<XTBG_ANNOUNCEMENT> XTBG_ANNOUNCEMENT { get; set; }
        public DbSet<XTBG_MEETING> XTBG_MEETING { get; set; }
        public DbSet<XTBG_FILE> XTBG_FILE { get; set; }
        public DbSet<XTBG_EMAIL> XTBG_EMAIL { get; set; }
    }
}
