//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBZGM.XTBG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OA_FINANCEAUDITS
    {
        public decimal FAID { get; set; }
        public Nullable<decimal> FINANCEID { get; set; }
        public Nullable<decimal> NEXTAUDITUSER { get; set; }
        public Nullable<decimal> ISAUDIT { get; set; }
        public Nullable<System.DateTime> AUDITTIME { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string AUDITCONTENT { get; set; }
    }
}
