//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBZGM.XTBG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OA_FINANCES
    {
        public decimal FINANCEID { get; set; }
        public string TITLE { get; set; }
        public string FILEPATH { get; set; }
        public Nullable<decimal> STATUS { get; set; }
        public string FILENAME { get; set; }
        public string PDFNAME { get; set; }
        public string PDFPATH { get; set; }
        public string REMARK { get; set; }
        public Nullable<decimal> CREATEUSERID { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
    }
}
