//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBZGM.XTBG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_USERS
    {
        public SYS_USERS()
        {
            this.SYS_USERROLES = new HashSet<SYS_USERROLES>();
        }
    
        public decimal USERID { get; set; }
        public string USERNAME { get; set; }
        public Nullable<decimal> UNITID { get; set; }
        public string ACCOUNT { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<decimal> USERPOSITIONID { get; set; }
        public Nullable<decimal> STATUSID { get; set; }
        public string PHONE { get; set; }
        public string SPHONE { get; set; }
        public string ZFZBH { get; set; }
        public string PHONEIMEI { get; set; }
        public string AVATAR { get; set; }
        public Nullable<decimal> SEQNO { get; set; }
        public string SEX { get; set; }
        public Nullable<System.DateTime> BIRTHDAY { get; set; }
        public string SLAVATAR { get; set; }
        public string SMALLAVATAR { get; set; }
        public Nullable<decimal> ISMESSAGE { get; set; }
        public Nullable<decimal> ISONLINE { get; set; }
        public Nullable<decimal> ISPOLICE { get; set; }
    
        public virtual SYS_UNITS SYS_UNITS { get; set; }
        public virtual SYS_USERPOSITIONS SYS_USERPOSITIONS { get; set; }
        public virtual ICollection<SYS_USERROLES> SYS_USERROLES { get; set; }
    }
}
