//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBZGM.XTBG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_UNITTYPES
    {
        public SYS_UNITTYPES()
        {
            this.SYS_UNITS = new HashSet<SYS_UNITS>();
        }
    
        public decimal UNITTYPEID { get; set; }
        public string UNITTYPENAME { get; set; }
    
        public virtual ICollection<SYS_UNITS> SYS_UNITS { get; set; }
    }
}
