//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBZGM.XTBG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_ZDXX
    {
        public decimal ATID { get; set; }
        public string ZD_ID { get; set; }
        public string ZDXX_ID { get; set; }
        public string FZDXX_ID { get; set; }
        public string ZDXX_NAME { get; set; }
        public decimal SFGD { get; set; }
        public decimal SFLJSC { get; set; }
        public string BZ { get; set; }
    }
}
