//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBZGM.XTBG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XTBG_ANNOUNCEMENT
    {
        public decimal ANNOUNCEMENTID { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public Nullable<decimal> CREATEUSERID { get; set; }
        public string CREATEUSERNAME { get; set; }
        public Nullable<decimal> ANNOUNCEMENTTYPE { get; set; }
        public string ANNOUNCEMENTTITLE { get; set; }
        public string ANNOUNCEMENTSCOPE { get; set; }
        public Nullable<System.DateTime> RELEASEDATE { get; set; }
        public Nullable<System.DateTime> EFFECTIVEDATE { get; set; }
        public string ANNOUNCEMENTATTACHMENTIDS { get; set; }
        public string ANNOUNCEMENTCONTENT { get; set; }
        public Nullable<decimal> STATUSID { get; set; }
        public Nullable<decimal> UNITID { get; set; }
        public string UNITNAME { get; set; }
        public string USERIDS2 { get; set; }
        public string ANNOUNCEMENTSCOPEID { get; set; }
    }
}
