//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBZGM.XTBG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XTBG_MEETINGROOM
    {
        public decimal MEETINGROOMID { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public Nullable<decimal> CREATEUSERID { get; set; }
        public string CREATEUSERNAME { get; set; }
        public string MEETINGROOMNAME { get; set; }
        public string MEETINGROOMADDR { get; set; }
        public Nullable<decimal> MGRUSERID { get; set; }
        public string MGRUSERNAME { get; set; }
        public Nullable<decimal> ACCOMMODATENUMBER { get; set; }
        public string EQUIPMENT { get; set; }
        public string REMARK { get; set; }
        public string PHOTO { get; set; }
        public Nullable<decimal> STATUSID { get; set; }
        public string AUTHORITYUNITIDS { get; set; }
        public string AUTHORITYUNITNAMES { get; set; }
    }
}
