//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBZGM.XTBG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XTBG_SCHEDULE
    {
        public decimal SCHEDULEID { get; set; }
        public Nullable<System.DateTime> STARTTIME { get; set; }
        public Nullable<System.DateTime> ENDTIME { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public Nullable<decimal> CREATEUSERID { get; set; }
        public string CREATEUSERNAME { get; set; }
        public string SCHEDULETITLE { get; set; }
        public string SCHEDULECONTENT { get; set; }
        public Nullable<decimal> SCHEDULETYPE { get; set; }
        public Nullable<decimal> STATUSID { get; set; }
    }
}
