//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBZGM.XTBG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XTBG_MEETING
    {
        public decimal MEETINGID { get; set; }
        public string MEETINGNAME { get; set; }
        public string MEETINGTITLE { get; set; }
        public string MEETINGCONTENT { get; set; }
        public Nullable<decimal> STATUSID { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public Nullable<decimal> CREATEUSERID { get; set; }
        public string CREATEUSERNAME { get; set; }
        public Nullable<System.DateTime> STARTTIME { get; set; }
        public Nullable<System.DateTime> ENDTIME { get; set; }
        public Nullable<decimal> MEETINGROOMID { get; set; }
        public string MEETINGROOMNAME { get; set; }
        public string MEETINGROOADDR { get; set; }
        public string USERIDS { get; set; }
        public string USERNAMES { get; set; }
        public string USERIDS2 { get; set; }
        public string USERNAMES2 { get; set; }
        public string USERPHONES { get; set; }
        public Nullable<decimal> SMSREMIND { get; set; }
        public string EXTERNALNUMBER { get; set; }
        public string ATTACHMENTIDS { get; set; }
        public Nullable<decimal> CREATEUNITID { get; set; }
        public string CREATEUNITNAME { get; set; }
    }
}
