//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBZGM.XTBG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XTBG_EMAIL
    {
        public decimal EMAILID { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public Nullable<decimal> CREATEUSERID { get; set; }
        public string CREATEUSERNAME { get; set; }
        public Nullable<decimal> SMSREMIND { get; set; }
        public string EXTERNALNUMBERS { get; set; }
        public string USERIDS { get; set; }
        public string USERNAMES { get; set; }
        public string EMAILTITLE { get; set; }
        public string EMAILCONTENT { get; set; }
        public string EMAILATTACHMENTIDS { get; set; }
        public Nullable<decimal> STATUSID { get; set; }
        public string REMINDCONTENT { get; set; }
        public Nullable<decimal> CREATEUNITID { get; set; }
        public string CREATEUNITNAME { get; set; }
        public string USERIDS2 { get; set; }
        public string USERNAMES2 { get; set; }
        public string USERPHONES { get; set; }
    }
}
