//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBZGM.XTBG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XTBG_SMS
    {
        public decimal SMSID { get; set; }
        public Nullable<decimal> STATUSID { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public Nullable<decimal> CREATEUSERID { get; set; }
        public string CREATEUSERNAME { get; set; }
        public Nullable<decimal> IDENTITY { get; set; }
        public string EXTERNALNUMBERS { get; set; }
        public string SMSCONTENT { get; set; }
        public string RECIPIENTUSERIDS { get; set; }
        public string RECIPIENTUSERNAMES { get; set; }
        public string MESSAGETITLE { get; set; }
        public string SEND { get; set; }
    }
}
