//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HZW.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ad_outadverts
    {
        public int ad_id { get; set; }
        public string id_type { get; set; }
        public Nullable<int> type_id { get; set; }
        public string ad_name { get; set; }
        public string unit { get; set; }
        public string unitperson { get; set; }
        public string unitphone { get; set; }
        public string producers { get; set; }
        public string prophone { get; set; }
        public Nullable<int> state { get; set; }
        public string examunit { get; set; }
        public System.DateTime examdate { get; set; }
        public System.DateTime startdate { get; set; }
        public System.DateTime enddate { get; set; }
        public string address { get; set; }
        public string photo1 { get; set; }
        public string photo2 { get; set; }
        public string photo3 { get; set; }
        public string grometry { get; set; }
        public Nullable<double> volume { get; set; }
        public Nullable<double> @long { get; set; }
        public Nullable<double> wide { get; set; }
        public Nullable<double> high { get; set; }
        public string materials { get; set; }
        public string curingunit { get; set; }
        public string superviseunit { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<int> createuserid { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual ad_classes ad_classes { get; set; }
    }
}
