//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HZW.ZHCG.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hzwEntities : DbContext
    {
        public hzwEntities()
            : base("name=hzwEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ad_classes> ad_classes { get; set; }
        public DbSet<ad_outadverts> ad_outadverts { get; set; }
        public DbSet<event_zfsjs> event_zfsjs { get; set; }
        public DbSet<mh_categors> mh_categors { get; set; }
        public DbSet<mh_news> mh_news { get; set; }
        public DbSet<store_bases> store_bases { get; set; }
        public DbSet<store_classes> store_classes { get; set; }
        public DbSet<sys_roles> sys_roles { get; set; }
        public DbSet<sys_units> sys_units { get; set; }
        public DbSet<sys_unittypes> sys_unittypes { get; set; }
        public DbSet<sys_userpositions> sys_userpositions { get; set; }
        public DbSet<sys_userroles> sys_userroles { get; set; }
        public DbSet<sys_users> sys_users { get; set; }
    }
}
