//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HZW.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class mh_categors
    {
        public mh_categors()
        {
            this.mh_news = new HashSet<mh_news>();
        }
    
        public int categoryid { get; set; }
        public string name { get; set; }
        public Nullable<int> seqno { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<int> prentid { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> isonline { get; set; }
    
        public virtual ICollection<mh_news> mh_news { get; set; }
    }
}
