//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HZW.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class mh_news
    {
        public int articleid { get; set; }
        public Nullable<int> categoryid { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public string author { get; set; }
        public Nullable<int> createuserid { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<int> status { get; set; }
        public string filename { get; set; }
        public string filepath { get; set; }
        public Nullable<int> isonline { get; set; }
        public Nullable<int> categoryid_bid { get; set; }
    
        public virtual mh_categors mh_categors { get; set; }
    }
}
