//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HZW.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_unittypes
    {
        public sys_unittypes()
        {
            this.sys_units = new HashSet<sys_units>();
        }
    
        public int UNITTYPEID { get; set; }
        public string UNITTYPENAME { get; set; }
    
        public virtual ICollection<sys_units> sys_units { get; set; }
    }
}
