//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HZW.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_userpositions
    {
        public sys_userpositions()
        {
            this.sys_users = new HashSet<sys_users>();
        }
    
        public int USERPOSITIONID { get; set; }
        public string USERPOSITIONNAME { get; set; }
    
        public virtual ICollection<sys_users> sys_users { get; set; }
    }
}
