//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateAPP.CmsServiceOut {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", ConfigurationName="CmsServiceOut.CuServicePortType")]
    public interface CuServicePortType {
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="urn:getResourceList", ReplyAction="urn:getResourceListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UpdateAPP.CmsServiceOut.getResourceListResponse getResourceList(UpdateAPP.CmsServiceOut.getResourceListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getResourceList", ReplyAction="urn:getResourceListResponse")]
        System.Threading.Tasks.Task<UpdateAPP.CmsServiceOut.getResourceListResponse> getResourceListAsync(UpdateAPP.CmsServiceOut.getResourceListRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="urn:searchVideoTags", ReplyAction="urn:searchVideoTagsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UpdateAPP.CmsServiceOut.searchVideoTagsResponse searchVideoTags(UpdateAPP.CmsServiceOut.searchVideoTagsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:searchVideoTags", ReplyAction="urn:searchVideoTagsResponse")]
        System.Threading.Tasks.Task<UpdateAPP.CmsServiceOut.searchVideoTagsResponse> searchVideoTagsAsync(UpdateAPP.CmsServiceOut.searchVideoTagsRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="urn:addVideoTag", ReplyAction="urn:addVideoTagResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UpdateAPP.CmsServiceOut.addVideoTagResponse addVideoTag(UpdateAPP.CmsServiceOut.addVideoTagRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:addVideoTag", ReplyAction="urn:addVideoTagResponse")]
        System.Threading.Tasks.Task<UpdateAPP.CmsServiceOut.addVideoTagResponse> addVideoTagAsync(UpdateAPP.CmsServiceOut.addVideoTagRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="urn:getStreamServiceByCameraIndexCodes", ReplyAction="urn:getStreamServiceByCameraIndexCodesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UpdateAPP.CmsServiceOut.getStreamServiceByCameraIndexCodesResponse getStreamServiceByCameraIndexCodes(UpdateAPP.CmsServiceOut.getStreamServiceByCameraIndexCodesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getStreamServiceByCameraIndexCodes", ReplyAction="urn:getStreamServiceByCameraIndexCodesResponse")]
        System.Threading.Tasks.Task<UpdateAPP.CmsServiceOut.getStreamServiceByCameraIndexCodesResponse> getStreamServiceByCameraIndexCodesAsync(UpdateAPP.CmsServiceOut.getStreamServiceByCameraIndexCodesRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="urn:getVrmServiceByCameraIndexCodes", ReplyAction="urn:getVrmServiceByCameraIndexCodesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UpdateAPP.CmsServiceOut.getVrmServiceByCameraIndexCodesResponse getVrmServiceByCameraIndexCodes(UpdateAPP.CmsServiceOut.getVrmServiceByCameraIndexCodesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getVrmServiceByCameraIndexCodes", ReplyAction="urn:getVrmServiceByCameraIndexCodesResponse")]
        System.Threading.Tasks.Task<UpdateAPP.CmsServiceOut.getVrmServiceByCameraIndexCodesResponse> getVrmServiceByCameraIndexCodesAsync(UpdateAPP.CmsServiceOut.getVrmServiceByCameraIndexCodesRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="urn:changePtzInfo", ReplyAction="urn:changePtzInfoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UpdateAPP.CmsServiceOut.changePtzInfoResponse changePtzInfo(UpdateAPP.CmsServiceOut.changePtzInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:changePtzInfo", ReplyAction="urn:changePtzInfoResponse")]
        System.Threading.Tasks.Task<UpdateAPP.CmsServiceOut.changePtzInfoResponse> changePtzInfoAsync(UpdateAPP.CmsServiceOut.changePtzInfoRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="urn:getAlarmHistory", ReplyAction="urn:getAlarmHistoryResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UpdateAPP.CmsServiceOut.getAlarmHistoryResponse getAlarmHistory(UpdateAPP.CmsServiceOut.getAlarmHistoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getAlarmHistory", ReplyAction="urn:getAlarmHistoryResponse")]
        System.Threading.Tasks.Task<UpdateAPP.CmsServiceOut.getAlarmHistoryResponse> getAlarmHistoryAsync(UpdateAPP.CmsServiceOut.getAlarmHistoryRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="urn:deleteVideoTag", ReplyAction="urn:deleteVideoTagResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UpdateAPP.CmsServiceOut.deleteVideoTagResponse deleteVideoTag(UpdateAPP.CmsServiceOut.deleteVideoTagRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:deleteVideoTag", ReplyAction="urn:deleteVideoTagResponse")]
        System.Threading.Tasks.Task<UpdateAPP.CmsServiceOut.deleteVideoTagResponse> deleteVideoTagAsync(UpdateAPP.CmsServiceOut.deleteVideoTagRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="urn:invoke", ReplyAction="urn:invokeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UpdateAPP.CmsServiceOut.invokeResponse invoke(UpdateAPP.CmsServiceOut.invokeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:invoke", ReplyAction="urn:invokeResponse")]
        System.Threading.Tasks.Task<UpdateAPP.CmsServiceOut.invokeResponse> invokeAsync(UpdateAPP.CmsServiceOut.invokeRequest request);
        
        // CODEGEN: 参数“token”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="urn:getNetZoneId", ReplyAction="urn:getNetZoneIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UpdateAPP.CmsServiceOut.getNetZoneIdResponse getNetZoneId(UpdateAPP.CmsServiceOut.getNetZoneIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getNetZoneId", ReplyAction="urn:getNetZoneIdResponse")]
        System.Threading.Tasks.Task<UpdateAPP.CmsServiceOut.getNetZoneIdResponse> getNetZoneIdAsync(UpdateAPP.CmsServiceOut.getNetZoneIdRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="urn:getPtzInfos", ReplyAction="urn:getPtzInfosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UpdateAPP.CmsServiceOut.getPtzInfosResponse getPtzInfos(UpdateAPP.CmsServiceOut.getPtzInfosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getPtzInfos", ReplyAction="urn:getPtzInfosResponse")]
        System.Threading.Tasks.Task<UpdateAPP.CmsServiceOut.getPtzInfosResponse> getPtzInfosAsync(UpdateAPP.CmsServiceOut.getPtzInfosRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="urn:deletePtzInfo", ReplyAction="urn:deletePtzInfoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UpdateAPP.CmsServiceOut.deletePtzInfoResponse deletePtzInfo(UpdateAPP.CmsServiceOut.deletePtzInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:deletePtzInfo", ReplyAction="urn:deletePtzInfoResponse")]
        System.Threading.Tasks.Task<UpdateAPP.CmsServiceOut.deletePtzInfoResponse> deletePtzInfoAsync(UpdateAPP.CmsServiceOut.deletePtzInfoRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="urn:savePresetInfo", ReplyAction="urn:savePresetInfoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UpdateAPP.CmsServiceOut.savePresetInfoResponse savePresetInfo(UpdateAPP.CmsServiceOut.savePresetInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:savePresetInfo", ReplyAction="urn:savePresetInfoResponse")]
        System.Threading.Tasks.Task<UpdateAPP.CmsServiceOut.savePresetInfoResponse> savePresetInfoAsync(UpdateAPP.CmsServiceOut.savePresetInfoRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="urn:getAlarmEventById", ReplyAction="urn:getAlarmEventByIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UpdateAPP.CmsServiceOut.getAlarmEventByIdResponse getAlarmEventById(UpdateAPP.CmsServiceOut.getAlarmEventByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getAlarmEventById", ReplyAction="urn:getAlarmEventByIdResponse")]
        System.Threading.Tasks.Task<UpdateAPP.CmsServiceOut.getAlarmEventByIdResponse> getAlarmEventByIdAsync(UpdateAPP.CmsServiceOut.getAlarmEventByIdRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="urn:getAlarmEventByRegion", ReplyAction="urn:getAlarmEventByRegionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UpdateAPP.CmsServiceOut.getAlarmEventByRegionResponse getAlarmEventByRegion(UpdateAPP.CmsServiceOut.getAlarmEventByRegionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getAlarmEventByRegion", ReplyAction="urn:getAlarmEventByRegionResponse")]
        System.Threading.Tasks.Task<UpdateAPP.CmsServiceOut.getAlarmEventByRegionResponse> getAlarmEventByRegionAsync(UpdateAPP.CmsServiceOut.getAlarmEventByRegionRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="urn:modifyVideoTag", ReplyAction="urn:modifyVideoTagResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UpdateAPP.CmsServiceOut.modifyVideoTagResponse modifyVideoTag(UpdateAPP.CmsServiceOut.modifyVideoTagRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:modifyVideoTag", ReplyAction="urn:modifyVideoTagResponse")]
        System.Threading.Tasks.Task<UpdateAPP.CmsServiceOut.modifyVideoTagResponse> modifyVideoTagAsync(UpdateAPP.CmsServiceOut.modifyVideoTagRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getResourceList", WrapperNamespace="http://ws.vms.ivms6.hikvision.com", IsWrapped=true)]
    public partial class getResourceListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string resourceTypeCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string resourceIndexCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=2)]
        public long netZoneId;
        
        public getResourceListRequest() {
        }
        
        public getResourceListRequest(string resourceTypeCode, string resourceIndexCode, long netZoneId) {
            this.resourceTypeCode = resourceTypeCode;
            this.resourceIndexCode = resourceIndexCode;
            this.netZoneId = netZoneId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getResourceListResponse", WrapperNamespace="http://ws.vms.ivms6.hikvision.com", IsWrapped=true)]
    public partial class getResourceListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public getResourceListResponse() {
        }
        
        public getResourceListResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchVideoTags", WrapperNamespace="http://ws.vms.ivms6.hikvision.com", IsWrapped=true)]
    public partial class searchVideoTagsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cameraIndexCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=1)]
        public long startTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=2)]
        public long stopTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string storePlace;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string remark;
        
        public searchVideoTagsRequest() {
        }
        
        public searchVideoTagsRequest(string cameraIndexCode, long startTime, long stopTime, string storePlace, string remark) {
            this.cameraIndexCode = cameraIndexCode;
            this.startTime = startTime;
            this.stopTime = stopTime;
            this.storePlace = storePlace;
            this.remark = remark;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchVideoTagsResponse", WrapperNamespace="http://ws.vms.ivms6.hikvision.com", IsWrapped=true)]
    public partial class searchVideoTagsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public searchVideoTagsResponse() {
        }
        
        public searchVideoTagsResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addVideoTag", WrapperNamespace="http://ws.vms.ivms6.hikvision.com", IsWrapped=true)]
    public partial class addVideoTagRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cameraIndexCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=1)]
        public long startTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=2)]
        public long stopTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string storePlace;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string remark;
        
        public addVideoTagRequest() {
        }
        
        public addVideoTagRequest(string cameraIndexCode, long startTime, long stopTime, string storePlace, string remark) {
            this.cameraIndexCode = cameraIndexCode;
            this.startTime = startTime;
            this.stopTime = stopTime;
            this.storePlace = storePlace;
            this.remark = remark;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addVideoTagResponse", WrapperNamespace="http://ws.vms.ivms6.hikvision.com", IsWrapped=true)]
    public partial class addVideoTagResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public addVideoTagResponse() {
        }
        
        public addVideoTagResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStreamServiceByCameraIndexCodes", WrapperNamespace="http://ws.vms.ivms6.hikvision.com", IsWrapped=true)]
    public partial class getStreamServiceByCameraIndexCodesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=1)]
        public int type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cameraIndexCodes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=3)]
        public long netZoneId;
        
        public getStreamServiceByCameraIndexCodesRequest() {
        }
        
        public getStreamServiceByCameraIndexCodesRequest(string token, int type, string cameraIndexCodes, long netZoneId) {
            this.token = token;
            this.type = type;
            this.cameraIndexCodes = cameraIndexCodes;
            this.netZoneId = netZoneId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStreamServiceByCameraIndexCodesResponse", WrapperNamespace="http://ws.vms.ivms6.hikvision.com", IsWrapped=true)]
    public partial class getStreamServiceByCameraIndexCodesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public getStreamServiceByCameraIndexCodesResponse() {
        }
        
        public getStreamServiceByCameraIndexCodesResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getVrmServiceByCameraIndexCodes", WrapperNamespace="http://ws.vms.ivms6.hikvision.com", IsWrapped=true)]
    public partial class getVrmServiceByCameraIndexCodesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cameraIndexCodes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=2)]
        public long netZoneId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string recordType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=4)]
        public int playWndIndex;
        
        public getVrmServiceByCameraIndexCodesRequest() {
        }
        
        public getVrmServiceByCameraIndexCodesRequest(string token, string cameraIndexCodes, long netZoneId, string recordType, int playWndIndex) {
            this.token = token;
            this.cameraIndexCodes = cameraIndexCodes;
            this.netZoneId = netZoneId;
            this.recordType = recordType;
            this.playWndIndex = playWndIndex;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getVrmServiceByCameraIndexCodesResponse", WrapperNamespace="http://ws.vms.ivms6.hikvision.com", IsWrapped=true)]
    public partial class getVrmServiceByCameraIndexCodesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public getVrmServiceByCameraIndexCodesResponse() {
        }
        
        public getVrmServiceByCameraIndexCodesResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="changePtzInfo", WrapperNamespace="http://ws.vms.ivms6.hikvision.com", IsWrapped=true)]
    public partial class changePtzInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cameraIndexCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=2)]
        public int type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=4)]
        public int num;
        
        public changePtzInfoRequest() {
        }
        
        public changePtzInfoRequest(string token, string cameraIndexCode, int type, string name, int num) {
            this.token = token;
            this.cameraIndexCode = cameraIndexCode;
            this.type = type;
            this.name = name;
            this.num = num;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="changePtzInfoResponse", WrapperNamespace="http://ws.vms.ivms6.hikvision.com", IsWrapped=true)]
    public partial class changePtzInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public changePtzInfoResponse() {
        }
        
        public changePtzInfoResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAlarmHistory", WrapperNamespace="http://ws.vms.ivms6.hikvision.com", IsWrapped=true)]
    public partial class getAlarmHistoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("sourceIndexCodes", IsNullable=true)]
        public string[] sourceIndexCodes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string beginTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string endTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=3)]
        public int pageNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=4)]
        public int pageSize;
        
        public getAlarmHistoryRequest() {
        }
        
        public getAlarmHistoryRequest(string[] sourceIndexCodes, string beginTime, string endTime, int pageNo, int pageSize) {
            this.sourceIndexCodes = sourceIndexCodes;
            this.beginTime = beginTime;
            this.endTime = endTime;
            this.pageNo = pageNo;
            this.pageSize = pageSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAlarmHistoryResponse", WrapperNamespace="http://ws.vms.ivms6.hikvision.com", IsWrapped=true)]
    public partial class getAlarmHistoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public getAlarmHistoryResponse() {
        }
        
        public getAlarmHistoryResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteVideoTag", WrapperNamespace="http://ws.vms.ivms6.hikvision.com", IsWrapped=true)]
    public partial class deleteVideoTagRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=0)]
        public int videoTagId;
        
        public deleteVideoTagRequest() {
        }
        
        public deleteVideoTagRequest(int videoTagId) {
            this.videoTagId = videoTagId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteVideoTagResponse", WrapperNamespace="http://ws.vms.ivms6.hikvision.com", IsWrapped=true)]
    public partial class deleteVideoTagResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public deleteVideoTagResponse() {
        }
        
        public deleteVideoTagResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="invoke", WrapperNamespace="http://ws.vms.ivms6.hikvision.com", IsWrapped=true)]
    public partial class invokeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string commandName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string argType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args;
        
        public invokeRequest() {
        }
        
        public invokeRequest(string commandName, string argType, string args) {
            this.commandName = commandName;
            this.argType = argType;
            this.args = args;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="invokeResponse", WrapperNamespace="http://ws.vms.ivms6.hikvision.com", IsWrapped=true)]
    public partial class invokeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public invokeResponse() {
        }
        
        public invokeResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getNetZoneId", WrapperNamespace="http://ws.vms.ivms6.hikvision.com", IsWrapped=true)]
    public partial class getNetZoneIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string vasIp;
        
        public getNetZoneIdRequest() {
        }
        
        public getNetZoneIdRequest(string token, string vasIp) {
            this.token = token;
            this.vasIp = vasIp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getNetZoneIdResponse", WrapperNamespace="http://ws.vms.ivms6.hikvision.com", IsWrapped=true)]
    public partial class getNetZoneIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=0)]
        public long @return;
        
        public getNetZoneIdResponse() {
        }
        
        public getNetZoneIdResponse(long @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPtzInfos", WrapperNamespace="http://ws.vms.ivms6.hikvision.com", IsWrapped=true)]
    public partial class getPtzInfosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cameraIndexCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=2)]
        public int type;
        
        public getPtzInfosRequest() {
        }
        
        public getPtzInfosRequest(string token, string cameraIndexCode, int type) {
            this.token = token;
            this.cameraIndexCode = cameraIndexCode;
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPtzInfosResponse", WrapperNamespace="http://ws.vms.ivms6.hikvision.com", IsWrapped=true)]
    public partial class getPtzInfosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public getPtzInfosResponse() {
        }
        
        public getPtzInfosResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deletePtzInfo", WrapperNamespace="http://ws.vms.ivms6.hikvision.com", IsWrapped=true)]
    public partial class deletePtzInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cameraIndexCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=2)]
        public int type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=3)]
        public int num;
        
        public deletePtzInfoRequest() {
        }
        
        public deletePtzInfoRequest(string token, string cameraIndexCode, int type, int num) {
            this.token = token;
            this.cameraIndexCode = cameraIndexCode;
            this.type = type;
            this.num = num;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deletePtzInfoResponse", WrapperNamespace="http://ws.vms.ivms6.hikvision.com", IsWrapped=true)]
    public partial class deletePtzInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public deletePtzInfoResponse() {
        }
        
        public deletePtzInfoResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="savePresetInfo", WrapperNamespace="http://ws.vms.ivms6.hikvision.com", IsWrapped=true)]
    public partial class savePresetInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cameraIndexCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=2)]
        public int type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=4)]
        public int num;
        
        public savePresetInfoRequest() {
        }
        
        public savePresetInfoRequest(string token, string cameraIndexCode, int type, string name, int num) {
            this.token = token;
            this.cameraIndexCode = cameraIndexCode;
            this.type = type;
            this.name = name;
            this.num = num;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="savePresetInfoResponse", WrapperNamespace="http://ws.vms.ivms6.hikvision.com", IsWrapped=true)]
    public partial class savePresetInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public savePresetInfoResponse() {
        }
        
        public savePresetInfoResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAlarmEventById", WrapperNamespace="http://ws.vms.ivms6.hikvision.com", IsWrapped=true)]
    public partial class getAlarmEventByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=0)]
        public int alarmEventId;
        
        public getAlarmEventByIdRequest() {
        }
        
        public getAlarmEventByIdRequest(int alarmEventId) {
            this.alarmEventId = alarmEventId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAlarmEventByIdResponse", WrapperNamespace="http://ws.vms.ivms6.hikvision.com", IsWrapped=true)]
    public partial class getAlarmEventByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public getAlarmEventByIdResponse() {
        }
        
        public getAlarmEventByIdResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAlarmEventByRegion", WrapperNamespace="http://ws.vms.ivms6.hikvision.com", IsWrapped=true)]
    public partial class getAlarmEventByRegionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string regionIndexCode;
        
        public getAlarmEventByRegionRequest() {
        }
        
        public getAlarmEventByRegionRequest(string regionIndexCode) {
            this.regionIndexCode = regionIndexCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAlarmEventByRegionResponse", WrapperNamespace="http://ws.vms.ivms6.hikvision.com", IsWrapped=true)]
    public partial class getAlarmEventByRegionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public getAlarmEventByRegionResponse() {
        }
        
        public getAlarmEventByRegionResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modifyVideoTag", WrapperNamespace="http://ws.vms.ivms6.hikvision.com", IsWrapped=true)]
    public partial class modifyVideoTagRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=0)]
        public int videoTagId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string remark;
        
        public modifyVideoTagRequest() {
        }
        
        public modifyVideoTagRequest(int videoTagId, string remark) {
            this.videoTagId = videoTagId;
            this.remark = remark;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modifyVideoTagResponse", WrapperNamespace="http://ws.vms.ivms6.hikvision.com", IsWrapped=true)]
    public partial class modifyVideoTagResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.vms.ivms6.hikvision.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public modifyVideoTagResponse() {
        }
        
        public modifyVideoTagResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CuServicePortTypeChannel : UpdateAPP.CmsServiceOut.CuServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CuServicePortTypeClient : System.ServiceModel.ClientBase<UpdateAPP.CmsServiceOut.CuServicePortType>, UpdateAPP.CmsServiceOut.CuServicePortType {
        
        public CuServicePortTypeClient() {
        }
        
        public CuServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CuServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CuServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CuServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UpdateAPP.CmsServiceOut.getResourceListResponse UpdateAPP.CmsServiceOut.CuServicePortType.getResourceList(UpdateAPP.CmsServiceOut.getResourceListRequest request) {
            return base.Channel.getResourceList(request);
        }
        
        public string getResourceList(string resourceTypeCode, string resourceIndexCode, long netZoneId) {
            UpdateAPP.CmsServiceOut.getResourceListRequest inValue = new UpdateAPP.CmsServiceOut.getResourceListRequest();
            inValue.resourceTypeCode = resourceTypeCode;
            inValue.resourceIndexCode = resourceIndexCode;
            inValue.netZoneId = netZoneId;
            UpdateAPP.CmsServiceOut.getResourceListResponse retVal = ((UpdateAPP.CmsServiceOut.CuServicePortType)(this)).getResourceList(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UpdateAPP.CmsServiceOut.getResourceListResponse> UpdateAPP.CmsServiceOut.CuServicePortType.getResourceListAsync(UpdateAPP.CmsServiceOut.getResourceListRequest request) {
            return base.Channel.getResourceListAsync(request);
        }
        
        public System.Threading.Tasks.Task<UpdateAPP.CmsServiceOut.getResourceListResponse> getResourceListAsync(string resourceTypeCode, string resourceIndexCode, long netZoneId) {
            UpdateAPP.CmsServiceOut.getResourceListRequest inValue = new UpdateAPP.CmsServiceOut.getResourceListRequest();
            inValue.resourceTypeCode = resourceTypeCode;
            inValue.resourceIndexCode = resourceIndexCode;
            inValue.netZoneId = netZoneId;
            return ((UpdateAPP.CmsServiceOut.CuServicePortType)(this)).getResourceListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UpdateAPP.CmsServiceOut.searchVideoTagsResponse UpdateAPP.CmsServiceOut.CuServicePortType.searchVideoTags(UpdateAPP.CmsServiceOut.searchVideoTagsRequest request) {
            return base.Channel.searchVideoTags(request);
        }
        
        public string searchVideoTags(string cameraIndexCode, long startTime, long stopTime, string storePlace, string remark) {
            UpdateAPP.CmsServiceOut.searchVideoTagsRequest inValue = new UpdateAPP.CmsServiceOut.searchVideoTagsRequest();
            inValue.cameraIndexCode = cameraIndexCode;
            inValue.startTime = startTime;
            inValue.stopTime = stopTime;
            inValue.storePlace = storePlace;
            inValue.remark = remark;
            UpdateAPP.CmsServiceOut.searchVideoTagsResponse retVal = ((UpdateAPP.CmsServiceOut.CuServicePortType)(this)).searchVideoTags(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UpdateAPP.CmsServiceOut.searchVideoTagsResponse> UpdateAPP.CmsServiceOut.CuServicePortType.searchVideoTagsAsync(UpdateAPP.CmsServiceOut.searchVideoTagsRequest request) {
            return base.Channel.searchVideoTagsAsync(request);
        }
        
        public System.Threading.Tasks.Task<UpdateAPP.CmsServiceOut.searchVideoTagsResponse> searchVideoTagsAsync(string cameraIndexCode, long startTime, long stopTime, string storePlace, string remark) {
            UpdateAPP.CmsServiceOut.searchVideoTagsRequest inValue = new UpdateAPP.CmsServiceOut.searchVideoTagsRequest();
            inValue.cameraIndexCode = cameraIndexCode;
            inValue.startTime = startTime;
            inValue.stopTime = stopTime;
            inValue.storePlace = storePlace;
            inValue.remark = remark;
            return ((UpdateAPP.CmsServiceOut.CuServicePortType)(this)).searchVideoTagsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UpdateAPP.CmsServiceOut.addVideoTagResponse UpdateAPP.CmsServiceOut.CuServicePortType.addVideoTag(UpdateAPP.CmsServiceOut.addVideoTagRequest request) {
            return base.Channel.addVideoTag(request);
        }
        
        public string addVideoTag(string cameraIndexCode, long startTime, long stopTime, string storePlace, string remark) {
            UpdateAPP.CmsServiceOut.addVideoTagRequest inValue = new UpdateAPP.CmsServiceOut.addVideoTagRequest();
            inValue.cameraIndexCode = cameraIndexCode;
            inValue.startTime = startTime;
            inValue.stopTime = stopTime;
            inValue.storePlace = storePlace;
            inValue.remark = remark;
            UpdateAPP.CmsServiceOut.addVideoTagResponse retVal = ((UpdateAPP.CmsServiceOut.CuServicePortType)(this)).addVideoTag(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UpdateAPP.CmsServiceOut.addVideoTagResponse> UpdateAPP.CmsServiceOut.CuServicePortType.addVideoTagAsync(UpdateAPP.CmsServiceOut.addVideoTagRequest request) {
            return base.Channel.addVideoTagAsync(request);
        }
        
        public System.Threading.Tasks.Task<UpdateAPP.CmsServiceOut.addVideoTagResponse> addVideoTagAsync(string cameraIndexCode, long startTime, long stopTime, string storePlace, string remark) {
            UpdateAPP.CmsServiceOut.addVideoTagRequest inValue = new UpdateAPP.CmsServiceOut.addVideoTagRequest();
            inValue.cameraIndexCode = cameraIndexCode;
            inValue.startTime = startTime;
            inValue.stopTime = stopTime;
            inValue.storePlace = storePlace;
            inValue.remark = remark;
            return ((UpdateAPP.CmsServiceOut.CuServicePortType)(this)).addVideoTagAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UpdateAPP.CmsServiceOut.getStreamServiceByCameraIndexCodesResponse UpdateAPP.CmsServiceOut.CuServicePortType.getStreamServiceByCameraIndexCodes(UpdateAPP.CmsServiceOut.getStreamServiceByCameraIndexCodesRequest request) {
            return base.Channel.getStreamServiceByCameraIndexCodes(request);
        }
        
        public string getStreamServiceByCameraIndexCodes(string token, int type, string cameraIndexCodes, long netZoneId) {
            UpdateAPP.CmsServiceOut.getStreamServiceByCameraIndexCodesRequest inValue = new UpdateAPP.CmsServiceOut.getStreamServiceByCameraIndexCodesRequest();
            inValue.token = token;
            inValue.type = type;
            inValue.cameraIndexCodes = cameraIndexCodes;
            inValue.netZoneId = netZoneId;
            UpdateAPP.CmsServiceOut.getStreamServiceByCameraIndexCodesResponse retVal = ((UpdateAPP.CmsServiceOut.CuServicePortType)(this)).getStreamServiceByCameraIndexCodes(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UpdateAPP.CmsServiceOut.getStreamServiceByCameraIndexCodesResponse> UpdateAPP.CmsServiceOut.CuServicePortType.getStreamServiceByCameraIndexCodesAsync(UpdateAPP.CmsServiceOut.getStreamServiceByCameraIndexCodesRequest request) {
            return base.Channel.getStreamServiceByCameraIndexCodesAsync(request);
        }
        
        public System.Threading.Tasks.Task<UpdateAPP.CmsServiceOut.getStreamServiceByCameraIndexCodesResponse> getStreamServiceByCameraIndexCodesAsync(string token, int type, string cameraIndexCodes, long netZoneId) {
            UpdateAPP.CmsServiceOut.getStreamServiceByCameraIndexCodesRequest inValue = new UpdateAPP.CmsServiceOut.getStreamServiceByCameraIndexCodesRequest();
            inValue.token = token;
            inValue.type = type;
            inValue.cameraIndexCodes = cameraIndexCodes;
            inValue.netZoneId = netZoneId;
            return ((UpdateAPP.CmsServiceOut.CuServicePortType)(this)).getStreamServiceByCameraIndexCodesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UpdateAPP.CmsServiceOut.getVrmServiceByCameraIndexCodesResponse UpdateAPP.CmsServiceOut.CuServicePortType.getVrmServiceByCameraIndexCodes(UpdateAPP.CmsServiceOut.getVrmServiceByCameraIndexCodesRequest request) {
            return base.Channel.getVrmServiceByCameraIndexCodes(request);
        }
        
        public string getVrmServiceByCameraIndexCodes(string token, string cameraIndexCodes, long netZoneId, string recordType, int playWndIndex) {
            UpdateAPP.CmsServiceOut.getVrmServiceByCameraIndexCodesRequest inValue = new UpdateAPP.CmsServiceOut.getVrmServiceByCameraIndexCodesRequest();
            inValue.token = token;
            inValue.cameraIndexCodes = cameraIndexCodes;
            inValue.netZoneId = netZoneId;
            inValue.recordType = recordType;
            inValue.playWndIndex = playWndIndex;
            UpdateAPP.CmsServiceOut.getVrmServiceByCameraIndexCodesResponse retVal = ((UpdateAPP.CmsServiceOut.CuServicePortType)(this)).getVrmServiceByCameraIndexCodes(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UpdateAPP.CmsServiceOut.getVrmServiceByCameraIndexCodesResponse> UpdateAPP.CmsServiceOut.CuServicePortType.getVrmServiceByCameraIndexCodesAsync(UpdateAPP.CmsServiceOut.getVrmServiceByCameraIndexCodesRequest request) {
            return base.Channel.getVrmServiceByCameraIndexCodesAsync(request);
        }
        
        public System.Threading.Tasks.Task<UpdateAPP.CmsServiceOut.getVrmServiceByCameraIndexCodesResponse> getVrmServiceByCameraIndexCodesAsync(string token, string cameraIndexCodes, long netZoneId, string recordType, int playWndIndex) {
            UpdateAPP.CmsServiceOut.getVrmServiceByCameraIndexCodesRequest inValue = new UpdateAPP.CmsServiceOut.getVrmServiceByCameraIndexCodesRequest();
            inValue.token = token;
            inValue.cameraIndexCodes = cameraIndexCodes;
            inValue.netZoneId = netZoneId;
            inValue.recordType = recordType;
            inValue.playWndIndex = playWndIndex;
            return ((UpdateAPP.CmsServiceOut.CuServicePortType)(this)).getVrmServiceByCameraIndexCodesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UpdateAPP.CmsServiceOut.changePtzInfoResponse UpdateAPP.CmsServiceOut.CuServicePortType.changePtzInfo(UpdateAPP.CmsServiceOut.changePtzInfoRequest request) {
            return base.Channel.changePtzInfo(request);
        }
        
        public string changePtzInfo(string token, string cameraIndexCode, int type, string name, int num) {
            UpdateAPP.CmsServiceOut.changePtzInfoRequest inValue = new UpdateAPP.CmsServiceOut.changePtzInfoRequest();
            inValue.token = token;
            inValue.cameraIndexCode = cameraIndexCode;
            inValue.type = type;
            inValue.name = name;
            inValue.num = num;
            UpdateAPP.CmsServiceOut.changePtzInfoResponse retVal = ((UpdateAPP.CmsServiceOut.CuServicePortType)(this)).changePtzInfo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UpdateAPP.CmsServiceOut.changePtzInfoResponse> UpdateAPP.CmsServiceOut.CuServicePortType.changePtzInfoAsync(UpdateAPP.CmsServiceOut.changePtzInfoRequest request) {
            return base.Channel.changePtzInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<UpdateAPP.CmsServiceOut.changePtzInfoResponse> changePtzInfoAsync(string token, string cameraIndexCode, int type, string name, int num) {
            UpdateAPP.CmsServiceOut.changePtzInfoRequest inValue = new UpdateAPP.CmsServiceOut.changePtzInfoRequest();
            inValue.token = token;
            inValue.cameraIndexCode = cameraIndexCode;
            inValue.type = type;
            inValue.name = name;
            inValue.num = num;
            return ((UpdateAPP.CmsServiceOut.CuServicePortType)(this)).changePtzInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UpdateAPP.CmsServiceOut.getAlarmHistoryResponse UpdateAPP.CmsServiceOut.CuServicePortType.getAlarmHistory(UpdateAPP.CmsServiceOut.getAlarmHistoryRequest request) {
            return base.Channel.getAlarmHistory(request);
        }
        
        public string getAlarmHistory(string[] sourceIndexCodes, string beginTime, string endTime, int pageNo, int pageSize) {
            UpdateAPP.CmsServiceOut.getAlarmHistoryRequest inValue = new UpdateAPP.CmsServiceOut.getAlarmHistoryRequest();
            inValue.sourceIndexCodes = sourceIndexCodes;
            inValue.beginTime = beginTime;
            inValue.endTime = endTime;
            inValue.pageNo = pageNo;
            inValue.pageSize = pageSize;
            UpdateAPP.CmsServiceOut.getAlarmHistoryResponse retVal = ((UpdateAPP.CmsServiceOut.CuServicePortType)(this)).getAlarmHistory(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UpdateAPP.CmsServiceOut.getAlarmHistoryResponse> UpdateAPP.CmsServiceOut.CuServicePortType.getAlarmHistoryAsync(UpdateAPP.CmsServiceOut.getAlarmHistoryRequest request) {
            return base.Channel.getAlarmHistoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<UpdateAPP.CmsServiceOut.getAlarmHistoryResponse> getAlarmHistoryAsync(string[] sourceIndexCodes, string beginTime, string endTime, int pageNo, int pageSize) {
            UpdateAPP.CmsServiceOut.getAlarmHistoryRequest inValue = new UpdateAPP.CmsServiceOut.getAlarmHistoryRequest();
            inValue.sourceIndexCodes = sourceIndexCodes;
            inValue.beginTime = beginTime;
            inValue.endTime = endTime;
            inValue.pageNo = pageNo;
            inValue.pageSize = pageSize;
            return ((UpdateAPP.CmsServiceOut.CuServicePortType)(this)).getAlarmHistoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UpdateAPP.CmsServiceOut.deleteVideoTagResponse UpdateAPP.CmsServiceOut.CuServicePortType.deleteVideoTag(UpdateAPP.CmsServiceOut.deleteVideoTagRequest request) {
            return base.Channel.deleteVideoTag(request);
        }
        
        public string deleteVideoTag(int videoTagId) {
            UpdateAPP.CmsServiceOut.deleteVideoTagRequest inValue = new UpdateAPP.CmsServiceOut.deleteVideoTagRequest();
            inValue.videoTagId = videoTagId;
            UpdateAPP.CmsServiceOut.deleteVideoTagResponse retVal = ((UpdateAPP.CmsServiceOut.CuServicePortType)(this)).deleteVideoTag(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UpdateAPP.CmsServiceOut.deleteVideoTagResponse> UpdateAPP.CmsServiceOut.CuServicePortType.deleteVideoTagAsync(UpdateAPP.CmsServiceOut.deleteVideoTagRequest request) {
            return base.Channel.deleteVideoTagAsync(request);
        }
        
        public System.Threading.Tasks.Task<UpdateAPP.CmsServiceOut.deleteVideoTagResponse> deleteVideoTagAsync(int videoTagId) {
            UpdateAPP.CmsServiceOut.deleteVideoTagRequest inValue = new UpdateAPP.CmsServiceOut.deleteVideoTagRequest();
            inValue.videoTagId = videoTagId;
            return ((UpdateAPP.CmsServiceOut.CuServicePortType)(this)).deleteVideoTagAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UpdateAPP.CmsServiceOut.invokeResponse UpdateAPP.CmsServiceOut.CuServicePortType.invoke(UpdateAPP.CmsServiceOut.invokeRequest request) {
            return base.Channel.invoke(request);
        }
        
        public string invoke(string commandName, string argType, string args) {
            UpdateAPP.CmsServiceOut.invokeRequest inValue = new UpdateAPP.CmsServiceOut.invokeRequest();
            inValue.commandName = commandName;
            inValue.argType = argType;
            inValue.args = args;
            UpdateAPP.CmsServiceOut.invokeResponse retVal = ((UpdateAPP.CmsServiceOut.CuServicePortType)(this)).invoke(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UpdateAPP.CmsServiceOut.invokeResponse> UpdateAPP.CmsServiceOut.CuServicePortType.invokeAsync(UpdateAPP.CmsServiceOut.invokeRequest request) {
            return base.Channel.invokeAsync(request);
        }
        
        public System.Threading.Tasks.Task<UpdateAPP.CmsServiceOut.invokeResponse> invokeAsync(string commandName, string argType, string args) {
            UpdateAPP.CmsServiceOut.invokeRequest inValue = new UpdateAPP.CmsServiceOut.invokeRequest();
            inValue.commandName = commandName;
            inValue.argType = argType;
            inValue.args = args;
            return ((UpdateAPP.CmsServiceOut.CuServicePortType)(this)).invokeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UpdateAPP.CmsServiceOut.getNetZoneIdResponse UpdateAPP.CmsServiceOut.CuServicePortType.getNetZoneId(UpdateAPP.CmsServiceOut.getNetZoneIdRequest request) {
            return base.Channel.getNetZoneId(request);
        }
        
        public long getNetZoneId(string token, string vasIp) {
            UpdateAPP.CmsServiceOut.getNetZoneIdRequest inValue = new UpdateAPP.CmsServiceOut.getNetZoneIdRequest();
            inValue.token = token;
            inValue.vasIp = vasIp;
            UpdateAPP.CmsServiceOut.getNetZoneIdResponse retVal = ((UpdateAPP.CmsServiceOut.CuServicePortType)(this)).getNetZoneId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UpdateAPP.CmsServiceOut.getNetZoneIdResponse> UpdateAPP.CmsServiceOut.CuServicePortType.getNetZoneIdAsync(UpdateAPP.CmsServiceOut.getNetZoneIdRequest request) {
            return base.Channel.getNetZoneIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<UpdateAPP.CmsServiceOut.getNetZoneIdResponse> getNetZoneIdAsync(string token, string vasIp) {
            UpdateAPP.CmsServiceOut.getNetZoneIdRequest inValue = new UpdateAPP.CmsServiceOut.getNetZoneIdRequest();
            inValue.token = token;
            inValue.vasIp = vasIp;
            return ((UpdateAPP.CmsServiceOut.CuServicePortType)(this)).getNetZoneIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UpdateAPP.CmsServiceOut.getPtzInfosResponse UpdateAPP.CmsServiceOut.CuServicePortType.getPtzInfos(UpdateAPP.CmsServiceOut.getPtzInfosRequest request) {
            return base.Channel.getPtzInfos(request);
        }
        
        public string getPtzInfos(string token, string cameraIndexCode, int type) {
            UpdateAPP.CmsServiceOut.getPtzInfosRequest inValue = new UpdateAPP.CmsServiceOut.getPtzInfosRequest();
            inValue.token = token;
            inValue.cameraIndexCode = cameraIndexCode;
            inValue.type = type;
            UpdateAPP.CmsServiceOut.getPtzInfosResponse retVal = ((UpdateAPP.CmsServiceOut.CuServicePortType)(this)).getPtzInfos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UpdateAPP.CmsServiceOut.getPtzInfosResponse> UpdateAPP.CmsServiceOut.CuServicePortType.getPtzInfosAsync(UpdateAPP.CmsServiceOut.getPtzInfosRequest request) {
            return base.Channel.getPtzInfosAsync(request);
        }
        
        public System.Threading.Tasks.Task<UpdateAPP.CmsServiceOut.getPtzInfosResponse> getPtzInfosAsync(string token, string cameraIndexCode, int type) {
            UpdateAPP.CmsServiceOut.getPtzInfosRequest inValue = new UpdateAPP.CmsServiceOut.getPtzInfosRequest();
            inValue.token = token;
            inValue.cameraIndexCode = cameraIndexCode;
            inValue.type = type;
            return ((UpdateAPP.CmsServiceOut.CuServicePortType)(this)).getPtzInfosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UpdateAPP.CmsServiceOut.deletePtzInfoResponse UpdateAPP.CmsServiceOut.CuServicePortType.deletePtzInfo(UpdateAPP.CmsServiceOut.deletePtzInfoRequest request) {
            return base.Channel.deletePtzInfo(request);
        }
        
        public string deletePtzInfo(string token, string cameraIndexCode, int type, int num) {
            UpdateAPP.CmsServiceOut.deletePtzInfoRequest inValue = new UpdateAPP.CmsServiceOut.deletePtzInfoRequest();
            inValue.token = token;
            inValue.cameraIndexCode = cameraIndexCode;
            inValue.type = type;
            inValue.num = num;
            UpdateAPP.CmsServiceOut.deletePtzInfoResponse retVal = ((UpdateAPP.CmsServiceOut.CuServicePortType)(this)).deletePtzInfo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UpdateAPP.CmsServiceOut.deletePtzInfoResponse> UpdateAPP.CmsServiceOut.CuServicePortType.deletePtzInfoAsync(UpdateAPP.CmsServiceOut.deletePtzInfoRequest request) {
            return base.Channel.deletePtzInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<UpdateAPP.CmsServiceOut.deletePtzInfoResponse> deletePtzInfoAsync(string token, string cameraIndexCode, int type, int num) {
            UpdateAPP.CmsServiceOut.deletePtzInfoRequest inValue = new UpdateAPP.CmsServiceOut.deletePtzInfoRequest();
            inValue.token = token;
            inValue.cameraIndexCode = cameraIndexCode;
            inValue.type = type;
            inValue.num = num;
            return ((UpdateAPP.CmsServiceOut.CuServicePortType)(this)).deletePtzInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UpdateAPP.CmsServiceOut.savePresetInfoResponse UpdateAPP.CmsServiceOut.CuServicePortType.savePresetInfo(UpdateAPP.CmsServiceOut.savePresetInfoRequest request) {
            return base.Channel.savePresetInfo(request);
        }
        
        public string savePresetInfo(string token, string cameraIndexCode, int type, string name, int num) {
            UpdateAPP.CmsServiceOut.savePresetInfoRequest inValue = new UpdateAPP.CmsServiceOut.savePresetInfoRequest();
            inValue.token = token;
            inValue.cameraIndexCode = cameraIndexCode;
            inValue.type = type;
            inValue.name = name;
            inValue.num = num;
            UpdateAPP.CmsServiceOut.savePresetInfoResponse retVal = ((UpdateAPP.CmsServiceOut.CuServicePortType)(this)).savePresetInfo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UpdateAPP.CmsServiceOut.savePresetInfoResponse> UpdateAPP.CmsServiceOut.CuServicePortType.savePresetInfoAsync(UpdateAPP.CmsServiceOut.savePresetInfoRequest request) {
            return base.Channel.savePresetInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<UpdateAPP.CmsServiceOut.savePresetInfoResponse> savePresetInfoAsync(string token, string cameraIndexCode, int type, string name, int num) {
            UpdateAPP.CmsServiceOut.savePresetInfoRequest inValue = new UpdateAPP.CmsServiceOut.savePresetInfoRequest();
            inValue.token = token;
            inValue.cameraIndexCode = cameraIndexCode;
            inValue.type = type;
            inValue.name = name;
            inValue.num = num;
            return ((UpdateAPP.CmsServiceOut.CuServicePortType)(this)).savePresetInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UpdateAPP.CmsServiceOut.getAlarmEventByIdResponse UpdateAPP.CmsServiceOut.CuServicePortType.getAlarmEventById(UpdateAPP.CmsServiceOut.getAlarmEventByIdRequest request) {
            return base.Channel.getAlarmEventById(request);
        }
        
        public string getAlarmEventById(int alarmEventId) {
            UpdateAPP.CmsServiceOut.getAlarmEventByIdRequest inValue = new UpdateAPP.CmsServiceOut.getAlarmEventByIdRequest();
            inValue.alarmEventId = alarmEventId;
            UpdateAPP.CmsServiceOut.getAlarmEventByIdResponse retVal = ((UpdateAPP.CmsServiceOut.CuServicePortType)(this)).getAlarmEventById(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UpdateAPP.CmsServiceOut.getAlarmEventByIdResponse> UpdateAPP.CmsServiceOut.CuServicePortType.getAlarmEventByIdAsync(UpdateAPP.CmsServiceOut.getAlarmEventByIdRequest request) {
            return base.Channel.getAlarmEventByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<UpdateAPP.CmsServiceOut.getAlarmEventByIdResponse> getAlarmEventByIdAsync(int alarmEventId) {
            UpdateAPP.CmsServiceOut.getAlarmEventByIdRequest inValue = new UpdateAPP.CmsServiceOut.getAlarmEventByIdRequest();
            inValue.alarmEventId = alarmEventId;
            return ((UpdateAPP.CmsServiceOut.CuServicePortType)(this)).getAlarmEventByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UpdateAPP.CmsServiceOut.getAlarmEventByRegionResponse UpdateAPP.CmsServiceOut.CuServicePortType.getAlarmEventByRegion(UpdateAPP.CmsServiceOut.getAlarmEventByRegionRequest request) {
            return base.Channel.getAlarmEventByRegion(request);
        }
        
        public string getAlarmEventByRegion(string regionIndexCode) {
            UpdateAPP.CmsServiceOut.getAlarmEventByRegionRequest inValue = new UpdateAPP.CmsServiceOut.getAlarmEventByRegionRequest();
            inValue.regionIndexCode = regionIndexCode;
            UpdateAPP.CmsServiceOut.getAlarmEventByRegionResponse retVal = ((UpdateAPP.CmsServiceOut.CuServicePortType)(this)).getAlarmEventByRegion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UpdateAPP.CmsServiceOut.getAlarmEventByRegionResponse> UpdateAPP.CmsServiceOut.CuServicePortType.getAlarmEventByRegionAsync(UpdateAPP.CmsServiceOut.getAlarmEventByRegionRequest request) {
            return base.Channel.getAlarmEventByRegionAsync(request);
        }
        
        public System.Threading.Tasks.Task<UpdateAPP.CmsServiceOut.getAlarmEventByRegionResponse> getAlarmEventByRegionAsync(string regionIndexCode) {
            UpdateAPP.CmsServiceOut.getAlarmEventByRegionRequest inValue = new UpdateAPP.CmsServiceOut.getAlarmEventByRegionRequest();
            inValue.regionIndexCode = regionIndexCode;
            return ((UpdateAPP.CmsServiceOut.CuServicePortType)(this)).getAlarmEventByRegionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UpdateAPP.CmsServiceOut.modifyVideoTagResponse UpdateAPP.CmsServiceOut.CuServicePortType.modifyVideoTag(UpdateAPP.CmsServiceOut.modifyVideoTagRequest request) {
            return base.Channel.modifyVideoTag(request);
        }
        
        public string modifyVideoTag(int videoTagId, string remark) {
            UpdateAPP.CmsServiceOut.modifyVideoTagRequest inValue = new UpdateAPP.CmsServiceOut.modifyVideoTagRequest();
            inValue.videoTagId = videoTagId;
            inValue.remark = remark;
            UpdateAPP.CmsServiceOut.modifyVideoTagResponse retVal = ((UpdateAPP.CmsServiceOut.CuServicePortType)(this)).modifyVideoTag(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UpdateAPP.CmsServiceOut.modifyVideoTagResponse> UpdateAPP.CmsServiceOut.CuServicePortType.modifyVideoTagAsync(UpdateAPP.CmsServiceOut.modifyVideoTagRequest request) {
            return base.Channel.modifyVideoTagAsync(request);
        }
        
        public System.Threading.Tasks.Task<UpdateAPP.CmsServiceOut.modifyVideoTagResponse> modifyVideoTagAsync(int videoTagId, string remark) {
            UpdateAPP.CmsServiceOut.modifyVideoTagRequest inValue = new UpdateAPP.CmsServiceOut.modifyVideoTagRequest();
            inValue.videoTagId = videoTagId;
            inValue.remark = remark;
            return ((UpdateAPP.CmsServiceOut.CuServicePortType)(this)).modifyVideoTagAsync(inValue);
        }
    }
}
