//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.WUA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BD_JCLKCXDXX
    {
        public BD_JCLKCXDXX()
        {
            this.BD_JCLKLJLDGX = new HashSet<BD_JCLKLJLDGX>();
            this.BD_JCLKRXDXX = new HashSet<BD_JCLKRXDXX>();
        }
    
        public decimal JCLKCXD_ID { get; set; }
        public Nullable<decimal> CXDCD { get; set; }
        public Nullable<decimal> CXDKD { get; set; }
        public Nullable<decimal> CXDMJ { get; set; }
        public Nullable<decimal> SWMX_ID { get; set; }
        public string DLTX { get; set; }
        public Nullable<decimal> ZXDXZB { get; set; }
        public Nullable<decimal> ZXDYZB { get; set; }
        public Nullable<decimal> GD { get; set; }
    
        public virtual BD_JCLKLDCXDXX BD_JCLKLDCXDXX { get; set; }
        public virtual ICollection<BD_JCLKLJLDGX> BD_JCLKLJLDGX { get; set; }
        public virtual ICollection<BD_JCLKRXDXX> BD_JCLKRXDXX { get; set; }
    }
}
