//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.WUA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BMD_BMDTYPE
    {
        public BMD_BMDTYPE()
        {
            this.BMD_WWBMD = new HashSet<BMD_WWBMD>();
        }
    
        public decimal TYPEID { get; set; }
        public string TYPENAME { get; set; }
        public Nullable<decimal> STATUS { get; set; }
    
        public virtual ICollection<BMD_WWBMD> BMD_WWBMD { get; set; }
    }
}
