//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.WUA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BP_FHLDJCXX
    {
        public decimal FHLD_ID { get; set; }
        public string FHLD_NAME { get; set; }
        public string FHLDDJ_TYPE { get; set; }
        public string FHLDLX_TYPE { get; set; }
        public string QYMS { get; set; }
        public Nullable<decimal> MJ { get; set; }
        public string CKJG { get; set; }
        public string BZ { get; set; }
        public Nullable<System.DateTime> JGRQ { get; set; }
        public Nullable<System.DateTime> YJRQ { get; set; }
        public Nullable<decimal> YHDW_ID { get; set; }
    
        public virtual BD_JCFHLDXX BD_JCFHLDXX { get; set; }
    }
}
