//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.WUA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BP_GCJGXX
    {
        public decimal GC_ID { get; set; }
        public Nullable<System.DateTime> JGRQ { get; set; }
        public string SFAQJG { get; set; }
        public Nullable<decimal> CQTS { get; set; }
        public string ZLJG { get; set; }
        public string JGSM { get; set; }
        public string TBR_ID { get; set; }
        public Nullable<System.DateTime> TBSJ { get; set; }
        public Nullable<decimal> JHGQ { get; set; }
        public Nullable<decimal> SJGQ { get; set; }
        public Nullable<System.DateTime> KGRQ { get; set; }
    
        public virtual BP_GCGKXX BP_GCGKXX { get; set; }
    }
}
