//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.WUA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BP_GCSGWTXX
    {
        public decimal GCSGWT_ID { get; set; }
        public Nullable<decimal> GC_ID { get; set; }
        public Nullable<System.DateTime> FXRQ { get; set; }
        public Nullable<decimal> SFKK { get; set; }
        public Nullable<decimal> KKJE { get; set; }
        public string WTSM { get; set; }
        public string TBR_ID { get; set; }
        public Nullable<System.DateTime> TBSJ { get; set; }
    
        public virtual BP_GCGKXX BP_GCGKXX { get; set; }
    }
}
