//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.WUA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BP_GCJCXX
    {
        public decimal JCGC_ID { get; set; }
        public string GCDZ { get; set; }
        public Nullable<decimal> GCMJ { get; set; }
        public string XJ_TYPE { get; set; }
        public Nullable<decimal> MKWS { get; set; }
        public Nullable<decimal> WKWS { get; set; }
        public string SFYMYS { get; set; }
        public string SFYCJRZY { get; set; }
        public string CKJG { get; set; }
        public string BZ { get; set; }
        public Nullable<System.DateTime> JGRQ { get; set; }
        public Nullable<System.DateTime> YJRQ { get; set; }
        public Nullable<decimal> YHDW_ID { get; set; }
    
        public virtual BD_JCGCXX BD_JCGCXX { get; set; }
    }
}
