//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.WUA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BP_GCGKXX
    {
        public BP_GCGKXX()
        {
            this.BP_GCSGJDXX = new HashSet<BP_GCSGJDXX>();
            this.BP_GCSGWTXX = new HashSet<BP_GCSGWTXX>();
            this.BP_GCSJXX = new HashSet<BP_GCSJXX>();
            this.BP_GCWHXX = new HashSet<BP_GCWHXX>();
            this.BP_GCXMFJ = new HashSet<BP_GCXMFJ>();
            this.BP_GCZJSYQKYB = new HashSet<BP_GCZJSYQKYB>();
        }
    
        public decimal GC_ID { get; set; }
        public string GC_NAME { get; set; }
        public string GCGCZT_ID { get; set; }
        public string GCDZ { get; set; }
        public string JSGM_TYPE { get; set; }
        public string GCLX_TYPE { get; set; }
        public string GCXZ_TYPE { get; set; }
        public Nullable<decimal> YSZJ { get; set; }
        public string JSNR { get; set; }
        public Nullable<System.DateTime> JHKGRQ { get; set; }
        public Nullable<System.DateTime> JHJGRQ { get; set; }
        public Nullable<decimal> SGGQ { get; set; }
        public Nullable<decimal> GCNRLX_ID { get; set; }
        public string TBR_ID { get; set; }
        public Nullable<System.DateTime> TBSJ { get; set; }
        public string SFZJ { get; set; }
        public Nullable<decimal> GLBM_ID { get; set; }
        public string GCBH { get; set; }
        public string LXYJ { get; set; }
        public string LXPZJG { get; set; }
        public Nullable<decimal> SFLJSC { get; set; }
        public string XEBZ { get; set; }
    
        public virtual BP_GCJGXX BP_GCJGXX { get; set; }
        public virtual ICollection<BP_GCSGJDXX> BP_GCSGJDXX { get; set; }
        public virtual ICollection<BP_GCSGWTXX> BP_GCSGWTXX { get; set; }
        public virtual ICollection<BP_GCSJXX> BP_GCSJXX { get; set; }
        public virtual ICollection<BP_GCWHXX> BP_GCWHXX { get; set; }
        public virtual ICollection<BP_GCXMFJ> BP_GCXMFJ { get; set; }
        public virtual BP_GCZBXX BP_GCZBXX { get; set; }
        public virtual ICollection<BP_GCZJSYQKYB> BP_GCZJSYQKYB { get; set; }
    }
}
