//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.WUA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CQGL_DRAWHOUSE
    {
        public decimal DWHID { get; set; }
        public Nullable<decimal> DRAWID { get; set; }
        public string RESIDENTIAL { get; set; }
        public string HOUSENUMBER { get; set; }
        public Nullable<decimal> AREA { get; set; }
        public string REMARKS { get; set; }
        public string FILENAME { get; set; }
        public string FILEPATH { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
    
        public virtual CQGL_DRAWS CQGL_DRAWS { get; set; }
    }
}
