//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.WUA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CQGL_DRAWS
    {
        public CQGL_DRAWS()
        {
            this.CQGL_DRAWHOUSE = new HashSet<CQGL_DRAWHOUSE>();
        }
    
        public decimal DRAWID { get; set; }
        public Nullable<decimal> HOUSEID { get; set; }
        public Nullable<System.DateTime> DRAWTIME { get; set; }
        public Nullable<decimal> HOUSECOUNT { get; set; }
        public Nullable<decimal> OVERAREA { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public Nullable<decimal> CREATEUSER { get; set; }
    
        public virtual ICollection<CQGL_DRAWHOUSE> CQGL_DRAWHOUSE { get; set; }
        public virtual CQGL_HOUSES CQGL_HOUSES { get; set; }
    }
}
