//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.WUA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CQGL_TRANSITIONS
    {
        public decimal TRANSITIONID { get; set; }
        public Nullable<decimal> HOUSEID { get; set; }
        public Nullable<System.DateTime> STARTTIME { get; set; }
        public Nullable<decimal> TERM { get; set; }
        public Nullable<decimal> STANDARDMONEY { get; set; }
        public Nullable<decimal> MONEY { get; set; }
        public Nullable<decimal> PLACEAREA { get; set; }
        public Nullable<System.DateTime> CREATTIME { get; set; }
    
        public virtual CQGL_HOUSES CQGL_HOUSES { get; set; }
    }
}
