//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.WUA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CQGL_CHECKOUT
    {
        public decimal CHID { get; set; }
        public Nullable<decimal> SIGNID { get; set; }
        public Nullable<decimal> HOUSEID { get; set; }
        public Nullable<System.DateTime> CHTIME { get; set; }
        public string CHUSER { get; set; }
        public string ACCOUNTUSER { get; set; }
        public Nullable<decimal> MONEY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public Nullable<decimal> CREATEUSER { get; set; }
    
        public virtual CQGL_SIGNS CQGL_SIGNS { get; set; }
    }
}
