//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.WUA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FI_CAMERA_THEME
    {
        public FI_CAMERA_THEME()
        {
            this.FI_CAMERA_ITEM = new HashSet<FI_CAMERA_ITEM>();
        }
    
        public decimal THEMEID { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> PARENTID { get; set; }
        public Nullable<decimal> ISLINE { get; set; }
        public string PATH { get; set; }
        public string NOTE { get; set; }
    
        public virtual ICollection<FI_CAMERA_ITEM> FI_CAMERA_ITEM { get; set; }
    }
}
