//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.WUA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FI_CAMERA_INFO
    {
        public FI_CAMERA_INFO()
        {
            this.FI_CAMERA_ITEM = new HashSet<FI_CAMERA_ITEM>();
        }
    
        public decimal CAMERA_ID { get; set; }
        public Nullable<decimal> REGION_ID { get; set; }
        public Nullable<decimal> DEVICE_ID { get; set; }
        public string INDEX_CODE { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> CAMERA_TYPE { get; set; }
        public Nullable<decimal> STREAM_TYPE { get; set; }
        public Nullable<decimal> PTZ_CONTROL_TYPE { get; set; }
        public Nullable<decimal> PIXEL { get; set; }
        public Nullable<decimal> PTZ_TYPE { get; set; }
        public Nullable<decimal> SOUND { get; set; }
        public Nullable<decimal> IS_ENABLE { get; set; }
        public Nullable<decimal> STATUS { get; set; }
        public Nullable<decimal> LONGITUDE { get; set; }
        public Nullable<decimal> LATITUDE { get; set; }
        public Nullable<decimal> ELEVATION { get; set; }
        public string INSTALL_PLACE { get; set; }
        public string NOTE { get; set; }
        public string PARAMETER { get; set; }
        public string PLAYBACK { get; set; }
        public string SCOPE { get; set; }
    
        public virtual ICollection<FI_CAMERA_ITEM> FI_CAMERA_ITEM { get; set; }
    }
}
