//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.WUA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FI_DRAWS
    {
        public decimal ID { get; set; }
        public string TYPE { get; set; }
        public string POINTS { get; set; }
        public Nullable<decimal> USERID { get; set; }
        public string NOTE { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
    
        public virtual SYS_USERS SYS_USERS { get; set; }
    }
}
