//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.WUA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GCGL_SIMPLEFILES
    {
        public string ATTRACHID { get; set; }
        public Nullable<decimal> ATTRACHSOURCE { get; set; }
        public string ATTRACHNAME { get; set; }
        public string ATTRACHPATH { get; set; }
        public string ATTRACHTYPE { get; set; }
        public string ATTRACHREMARK { get; set; }
        public Nullable<decimal> SOURCETABLEID { get; set; }
    }
}
