//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.WUA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OA_CONTACTS
    {
        public decimal CONTACTID { get; set; }
        public Nullable<decimal> CONTACTGROUPID { get; set; }
        public Nullable<decimal> USERID { get; set; }
    
        public virtual OA_CONTACTGROUPS OA_CONTACTGROUPS { get; set; }
    }
}
