//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.WUA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OA_FILES
    {
        public OA_FILES()
        {
            this.OA_USERFILES = new HashSet<OA_USERFILES>();
        }
    
        public decimal FILEID { get; set; }
        public string FILENUMBER { get; set; }
        public string FILETITLE { get; set; }
        public string FILECONTENT { get; set; }
        public string FILENAME { get; set; }
        public string FILEPATH { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public Nullable<decimal> CREATEUSERID { get; set; }
    
        public virtual ICollection<OA_USERFILES> OA_USERFILES { get; set; }
    }
}
