//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.WUA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OA_USERMEETINGS
    {
        public decimal MTID { get; set; }
        public Nullable<decimal> MEETINGID { get; set; }
        public Nullable<decimal> USERID { get; set; }
        public Nullable<decimal> ISREAD { get; set; }
        public Nullable<decimal> ISLEAVE { get; set; }
        public Nullable<decimal> ISAPPROVE { get; set; }
        public string APPROVECONTENT { get; set; }
        public Nullable<decimal> ISPARTIN { get; set; }
        public string LEAVECONTENT { get; set; }
        public Nullable<System.DateTime> LEAVETIME { get; set; }
        public Nullable<System.DateTime> APPROVETIME { get; set; }
    
        public virtual OA_MEETINGS OA_MEETINGS { get; set; }
    }
}
