//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.WUA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PJKH_EXAMINES
    {
        public decimal EXAMINEID { get; set; }
        public Nullable<System.DateTime> EXAMINETIME { get; set; }
        public Nullable<decimal> USERID { get; set; }
        public Nullable<decimal> JOB { get; set; }
        public Nullable<decimal> SIGNIN { get; set; }
        public Nullable<decimal> ALARM { get; set; }
        public Nullable<decimal> SCORE { get; set; }
        public string REMARKS { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public Nullable<decimal> CREATEUSER { get; set; }
    }
}
