//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.WUA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class QWGL_CARALARMERRORCATCH
    {
        public decimal ID { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public Nullable<decimal> LONGITUDE { get; set; }
        public Nullable<decimal> LATITUDE { get; set; }
        public Nullable<decimal> X { get; set; }
        public Nullable<decimal> Y { get; set; }
        public Nullable<System.DateTime> GPSTIME { get; set; }
        public Nullable<decimal> SPEED { get; set; }
        public Nullable<System.DateTime> ALARMSTARTTIME { get; set; }
        public Nullable<System.DateTime> ALARMENDTIME { get; set; }
        public Nullable<decimal> ALARMTYPE { get; set; }
        public Nullable<decimal> CARID { get; set; }
    }
}
