//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.WUA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class QWGL_USERLATESTPOSITIONS
    {
        public decimal USERID { get; set; }
        public Nullable<decimal> X84 { get; set; }
        public Nullable<decimal> Y84 { get; set; }
        public Nullable<System.DateTime> POSITIONTIME { get; set; }
        public string IMEICODE { get; set; }
        public Nullable<System.DateTime> LASTLOGINTIME { get; set; }
        public Nullable<decimal> X2000 { get; set; }
        public Nullable<decimal> Y2000 { get; set; }
    }
}
