//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.WUA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class QWGL_CARLATESTPOSITIONS
    {
        public string CLNID { get; set; }
        public Nullable<decimal> CARID { get; set; }
        public Nullable<decimal> SPEED { get; set; }
        public Nullable<decimal> DIRECTION { get; set; }
        public Nullable<decimal> MILEAGE { get; set; }
        public Nullable<decimal> ISOVERAREA { get; set; }
        public Nullable<decimal> X84 { get; set; }
        public Nullable<decimal> Y84 { get; set; }
        public Nullable<decimal> X2000 { get; set; }
        public Nullable<decimal> Y2000 { get; set; }
        public Nullable<System.DateTime> LOCATETIME { get; set; }
        public Nullable<System.DateTime> RECIEVETIME { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string CARNUMBER { get; set; }
    
        public virtual QWGL_CARS QWGL_CARS { get; set; }
    }
}
