//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.WUA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class QWGL_CARTASKRAREARS
    {
        public decimal CTARID { get; set; }
        public Nullable<decimal> CARTASKID { get; set; }
        public Nullable<decimal> AREAID { get; set; }
    
        public virtual QWGL_AREAS QWGL_AREAS { get; set; }
        public virtual QWGL_CARTASKS QWGL_CARTASKS { get; set; }
    }
}
