//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.WUA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class QWGL_LEAVETYPES
    {
        public QWGL_LEAVETYPES()
        {
            this.QWGL_LEAVES = new HashSet<QWGL_LEAVES>();
        }
    
        public decimal LTYPEID { get; set; }
        public string LNAME { get; set; }
    
        public virtual ICollection<QWGL_LEAVES> QWGL_LEAVES { get; set; }
    }
}
