//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.WUA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_FUNCTIONS
    {
        public SYS_FUNCTIONS()
        {
            this.SYS_ROLEFUNCTIONS = new HashSet<SYS_ROLEFUNCTIONS>();
        }
    
        public decimal FUNCTIONID { get; set; }
        public string NAME { get; set; }
        public string CODE { get; set; }
        public Nullable<decimal> PARENTID { get; set; }
        public string PATH { get; set; }
        public string URL { get; set; }
        public Nullable<decimal> STATUSID { get; set; }
        public string ICONPATH { get; set; }
        public Nullable<decimal> SEQNUM { get; set; }
    
        public virtual ICollection<SYS_ROLEFUNCTIONS> SYS_ROLEFUNCTIONS { get; set; }
    }
}
