//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.WUA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_ZONES
    {
        public SYS_ZONES()
        {
            this.WJGL_NONBUILDINGS = new HashSet<WJGL_NONBUILDINGS>();
        }
    
        public decimal ZONEID { get; set; }
        public string ZONENAME { get; set; }
        public string ZONE84 { get; set; }
        public string ZONE2000 { get; set; }
        public string ZONECONTENT { get; set; }
        public string REMARK { get; set; }
    
        public virtual ICollection<WJGL_NONBUILDINGS> WJGL_NONBUILDINGS { get; set; }
    }
}
