//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.WUA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TJ_PERSONSIGNIN_TODAY
    {
        public decimal PERSONID { get; set; }
        public Nullable<decimal> UNITID { get; set; }
        public Nullable<System.DateTime> SIGNINTIME { get; set; }
        public Nullable<System.DateTime> SIGNOUTTIME { get; set; }
        public string UNITNAME { get; set; }
    }
}
