//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.WUA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_WORKFLOWSPECIFICS
    {
        public WF_WORKFLOWSPECIFICS()
        {
            this.WF_WORKFLOWSPECIFICACTIVITYS = new HashSet<WF_WORKFLOWSPECIFICACTIVITYS>();
        }
    
        public string WFSID { get; set; }
        public string WFID { get; set; }
        public string TABLENAME { get; set; }
        public Nullable<decimal> CREATEUSERID { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public Nullable<decimal> STATUS { get; set; }
        public string TABLENAMEID { get; set; }
        public string WFSNAME { get; set; }
        public string CURRENTWFSAID { get; set; }
        public Nullable<decimal> FILESTATUS { get; set; }
    
        public virtual WF_WORKFLOWS WF_WORKFLOWS { get; set; }
        public virtual ICollection<WF_WORKFLOWSPECIFICACTIVITYS> WF_WORKFLOWSPECIFICACTIVITYS { get; set; }
    }
}
