//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.WUA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_WORKFLOWSPECIFICUSERS
    {
        public WF_WORKFLOWSPECIFICUSERS()
        {
            this.WF_WORKFLOWSPECIFICUSERFILES = new HashSet<WF_WORKFLOWSPECIFICUSERFILES>();
        }
    
        public string WFSUID { get; set; }
        public Nullable<decimal> USERID { get; set; }
        public string CONTENT { get; set; }
        public Nullable<System.DateTime> DEALTIME { get; set; }
        public Nullable<decimal> STATUS { get; set; }
        public string WFSAID { get; set; }
        public Nullable<decimal> CREATEUSERID { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public Nullable<decimal> ISMAINUSER { get; set; }
        public string REMARK { get; set; }
    
        public virtual WF_WORKFLOWSPECIFICACTIVITYS WF_WORKFLOWSPECIFICACTIVITYS { get; set; }
        public virtual ICollection<WF_WORKFLOWSPECIFICUSERFILES> WF_WORKFLOWSPECIFICUSERFILES { get; set; }
    }
}
