//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.WUA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class XTGL_ZFSJS
    {
        public XTGL_ZFSJS()
        {
            this.XTGL_INSPECTIONIDEAS = new HashSet<XTGL_INSPECTIONIDEAS>();
        }
    
        public string ZFSJID { get; set; }
        public string WFID { get; set; }
        public string EVENTTITLE { get; set; }
        public Nullable<decimal> SOURCEID { get; set; }
        public string CONTACT { get; set; }
        public string CONTACTPHONE { get; set; }
        public string EVENTADDRESS { get; set; }
        public string EVENTCONTENT { get; set; }
        public Nullable<decimal> BCLASSID { get; set; }
        public Nullable<decimal> SCLASSID { get; set; }
        public Nullable<System.DateTime> FOUNDTIME { get; set; }
        public Nullable<decimal> LEVELNUM { get; set; }
        public Nullable<decimal> X84 { get; set; }
        public Nullable<System.DateTime> CREATETTIME { get; set; }
        public Nullable<decimal> CREATEUSERID { get; set; }
        public string IMEICODE { get; set; }
        public string REMARK1 { get; set; }
        public string REMARK2 { get; set; }
        public string REMARK3 { get; set; }
        public Nullable<decimal> Y84 { get; set; }
        public Nullable<decimal> X2000 { get; set; }
        public Nullable<decimal> Y2000 { get; set; }
        public string GEOMETRY { get; set; }
        public Nullable<decimal> ZONEID { get; set; }
        public Nullable<decimal> ISOVERDUE { get; set; }
        public Nullable<decimal> OVERDUELONG { get; set; }
        public Nullable<decimal> DISPOSELIMIT { get; set; }
        public Nullable<System.DateTime> OVERTIME { get; set; }
        public string EVENTCODE { get; set; }
    
        public virtual ICollection<XTGL_INSPECTIONIDEAS> XTGL_INSPECTIONIDEAS { get; set; }
        public virtual XTGL_ZFSJSOURCES XTGL_ZFSJSOURCES { get; set; }
    }
}
