//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.WUA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class XTGL_CLASSES
    {
        public decimal CLASSID { get; set; }
        public Nullable<decimal> PARENTID { get; set; }
        public string CLASSNAME { get; set; }
        public Nullable<decimal> CLASSCODE { get; set; }
        public string PATH { get; set; }
        public Nullable<decimal> SQENUM { get; set; }
    }
}
