//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGM.WUA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class XTGL_ZFSJSOURCES
    {
        public XTGL_ZFSJSOURCES()
        {
            this.XTGL_ZFSJS = new HashSet<XTGL_ZFSJS>();
        }
    
        public decimal SOURCEID { get; set; }
        public string SOURCENAME { get; set; }
        public string DESCRIPTION { get; set; }
    
        public virtual ICollection<XTGL_ZFSJS> XTGL_ZFSJS { get; set; }
    }
}
